export const fieldKeys = ["software", "security", "hardware", "electronics"];

export const fields = [
  {
    id: "software",
    tone: "software",
    title: { tr: "Yazılım", en: "Software" },
    short: {
      tr: "Web, mobil, veri, yapay zekâ ve ürün geliştirmeye açılan esnek bir yol.",
      en: "A flexible path into web, mobile, data, AI, and product development.",
    },
    description: {
      tr: "Yazılım, problemleri kodla modelleyip çalışan ürünlere dönüştürme işidir. Hata ayıklama, mantık kurma, kullanıcıyı düşünme ve sürekli öğrenme bu alanın merkezindedir.",
      en: "Software turns problems into working products through code. Debugging, logic, user thinking, and continuous learning sit at the center of the field.",
    },
    likes: {
      tr: ["Problem çözmek", "Kodla bir şey üretmek", "Hızlı prototip çıkarmak", "Kendi başına araştırmak"],
      en: ["Solving problems", "Building with code", "Rapid prototyping", "Independent research"],
    },
    struggles: {
      tr: ["Uzun hata ayıklama süreleri", "Soyut düşünme", "Sürekli yeni araç öğrenme", "Ekran başında çalışma"],
      en: ["Long debugging sessions", "Abstract thinking", "Learning new tools often", "Working at a screen"],
    },
    departments: {
      tr: ["Bilgisayar Mühendisliği", "Yazılım Mühendisliği", "Yapay Zekâ Mühendisliği", "Yönetim Bilişim Sistemleri"],
      en: ["Computer Engineering", "Software Engineering", "AI Engineering", "Management Information Systems"],
    },
    daily: {
      tr: "Kod yazma, test etme, hata bulma, ekiple karar alma ve kullanıcı problemini sade çözümlere bölme.",
      en: "Writing code, testing, debugging, making decisions with a team, and breaking user problems into smaller solutions.",
    },
    project: {
      title: { tr: "Bölüm Seçim Mini Sitesi", en: "Major Choice Mini Site" },
      time: { tr: "3 gün", en: "3 days" },
      difficulty: { tr: "Başlangıç", en: "Beginner" },
      output: {
        tr: "Ana sayfa, 5 soruluk test ve sonuç ekranı olan küçük site.",
        en: "A small site with a home page, 5-question quiz, and result screen.",
      },
    },
    strengths: {
      tr: ["Ürün çıkarma hızı yüksektir", "Portfolyo yapmak kolaydır", "Birden fazla alana geçiş yapılabilir"],
      en: ["Fast product output", "Easy to build a portfolio", "Can branch into many areas"],
    },
    cautions: {
      tr: ["Sadece video izlemek yetmez", "Hata ayıklama sabrı gerekir", "Temel matematik ve algoritma önemlidir"],
      en: ["Watching videos is not enough", "Debugging patience matters", "Math and algorithms are important"],
    },
  },
  {
    id: "security",
    tone: "security",
    title: { tr: "Siber Güvenlik", en: "Cybersecurity" },
    short: {
      tr: "Sistemleri anlamak, riskleri bulmak ve savunmayı güçlendirmek isteyenler için.",
      en: "For people who want to understand systems, find risks, and strengthen defenses.",
    },
    description: {
      tr: "Siber güvenlik; yazılımı, ağı, işletim sistemini ve insan hatalarını birlikte düşünür. Etik sınırlar, doküman okuma ve detay dikkati bu alanda çok önemlidir.",
      en: "Cybersecurity combines software, networks, operating systems, and human mistakes. Ethics, documentation, and attention to detail matter deeply.",
    },
    likes: {
      tr: ["Sistemleri incelemek", "Ağ mantığını anlamak", "Detay yakalamak", "Yasal lablarda pratik yapmak"],
      en: ["Exploring systems", "Understanding networks", "Catching details", "Practicing in legal labs"],
    },
    struggles: {
      tr: ["Belirsiz hatalar", "Çok doküman okumak", "Etik sınırlara dikkat etmek", "Temel yazılım/ağ bilgisi eksiği"],
      en: ["Ambiguous issues", "Reading lots of docs", "Respecting ethical boundaries", "Missing software/network basics"],
    },
    departments: {
      tr: ["Bilgisayar Mühendisliği", "Yazılım Mühendisliği", "Siber Güvenlik Programları", "Elektrik-Elektronik"],
      en: ["Computer Engineering", "Software Engineering", "Cybersecurity Programs", "Electrical-Electronics"],
    },
    daily: {
      tr: "Log okuma, ağ trafiğini inceleme, zafiyet araştırma, raporlama ve sistemleri daha güvenli hale getirme.",
      en: "Reading logs, inspecting network traffic, researching vulnerabilities, reporting, and hardening systems.",
    },
    project: {
      title: { tr: "Yasal Lab ve Linux Görevi", en: "Legal Lab and Linux Task" },
      time: { tr: "3 gün", en: "3 days" },
      difficulty: { tr: "Başlangıç-Orta", en: "Beginner-Intermediate" },
      output: {
        tr: "Temel Linux komutları, IP/port/DNS notları ve 2 kolay CTF/lab çözümü.",
        en: "Basic Linux commands, IP/port/DNS notes, and 2 easy CTF/lab solves.",
      },
    },
    strengths: {
      tr: ["Sistem düşünmeyi güçlendirir", "Savunma ve analiz becerisi kazandırır", "Meraklı insanlar için derin bir alandır"],
      en: ["Builds systems thinking", "Develops defense and analysis skills", "Deep field for curious people"],
    },
    cautions: {
      tr: ["İzinsiz deneme yasal değildir", "Temel ağ bilgisi gerekir", "Raporlama becerisi de önemlidir"],
      en: ["Unauthorized testing is illegal", "Network basics are required", "Reporting skills matter too"],
    },
  },
  {
    id: "hardware",
    tone: "hardware",
    title: { tr: "Donanım / Gömülü Sistemler", en: "Hardware / Embedded" },
    short: {
      tr: "Kodun fiziksel dünyada sonuç vermesini sevenler için sensör, kart ve robotik yolu.",
      en: "For people who like seeing code affect the physical world through sensors, boards, and robotics.",
    },
    description: {
      tr: "Donanım ve gömülü sistemler, yazılımı kartlar, sensörler, motorlar ve cihazlarla buluşturur. Sabırlı test, düşük seviye düşünme ve fiziksel prototip geliştirme bu alanda önemlidir.",
      en: "Hardware and embedded systems connect software with boards, sensors, motors, and devices. Patient testing, low-level thinking, and physical prototypes matter.",
    },
    likes: {
      tr: ["Arduino/ESP32 denemek", "Sensör okumak", "Robotik", "Kodun fiziksel sonucunu görmek"],
      en: ["Trying Arduino/ESP32", "Reading sensors", "Robotics", "Seeing physical output from code"],
    },
    struggles: {
      tr: ["Kablo/devre hataları", "C/C++ zorluğu", "Yavaş deneme döngüsü", "Elektronik temeli eksiği"],
      en: ["Wiring/circuit issues", "C/C++ difficulty", "Slower testing loops", "Missing electronics basics"],
    },
    departments: {
      tr: ["Bilgisayar Mühendisliği", "Elektrik-Elektronik", "Mekatronik", "Kontrol ve Otomasyon"],
      en: ["Computer Engineering", "Electrical-Electronics", "Mechatronics", "Control and Automation"],
    },
    daily: {
      tr: "Kart programlama, sensör verisi okuma, devre kontrolü, test yapma ve fiziksel prototip iyileştirme.",
      en: "Programming boards, reading sensor data, checking circuits, testing, and improving physical prototypes.",
    },
    project: {
      title: { tr: "Sensörlü Mini Sistem", en: "Mini Sensor System" },
      time: { tr: "3 gün", en: "3 days" },
      difficulty: { tr: "Orta", en: "Intermediate" },
      output: {
        tr: "Arduino/ESP32 veya simülatör ile sensör verisi okuyup ekrana/LED'e yansıtma.",
        en: "Read sensor data with Arduino/ESP32 or a simulator and show it on screen/LED.",
      },
    },
    strengths: {
      tr: ["Fiziksel ürün hissi verir", "Robotik ve IoT'ye açılır", "Yazılım + elektronik köprüsü kurar"],
      en: ["Feels like building a physical product", "Opens into robotics and IoT", "Bridges software and electronics"],
    },
    cautions: {
      tr: ["Parça ve ekipman gerekebilir", "Hatalar bazen koddan değil devreden gelir", "Sabırlı olmak gerekir"],
      en: ["Parts and equipment may be needed", "Bugs may come from circuits, not code", "Patience is required"],
    },
  },
  {
    id: "electronics",
    tone: "electronics",
    title: { tr: "Elektronik", en: "Electronics" },
    short: {
      tr: "Devre, sinyal, fizik ve sistem temeliyle daha derin mühendislik isteyenler için.",
      en: "For people who want deeper engineering through circuits, signals, physics, and systems.",
    },
    description: {
      tr: "Elektronik; devrelerin, sinyallerin, güç sistemlerinin ve haberleşmenin temelini anlamaya odaklanır. Matematik ve fizikle arası iyi olanlar için güçlü bir yoldur.",
      en: "Electronics focuses on understanding circuits, signals, power systems, and communication. It is a strong path for people comfortable with math and physics.",
    },
    likes: {
      tr: ["Devre analizi", "Fizik ve matematik", "Sinyal/haberleşme", "Laboratuvar çalışması"],
      en: ["Circuit analysis", "Physics and math", "Signals/communication", "Lab work"],
    },
    struggles: {
      tr: ["Teorik ders yoğunluğu", "Matematik ağırlığı", "Soyut sinyal kavramları", "Laboratuvar disiplini"],
      en: ["Heavy theory", "Math intensity", "Abstract signal concepts", "Lab discipline"],
    },
    departments: {
      tr: ["Elektrik-Elektronik Mühendisliği", "Elektronik ve Haberleşme", "Mekatronik", "Kontrol ve Otomasyon"],
      en: ["Electrical-Electronics Engineering", "Electronics and Communication", "Mechatronics", "Control and Automation"],
    },
    daily: {
      tr: "Devre tasarlama, ölçüm yapma, simülasyon kurma, sinyal yorumlama ve teoriyi fiziksel sistemlerle birleştirme.",
      en: "Designing circuits, measuring, simulating, interpreting signals, and connecting theory to physical systems.",
    },
    project: {
      title: { tr: "Devre Simülatörü Deneyi", en: "Circuit Simulator Experiment" },
      time: { tr: "3 gün", en: "3 days" },
      difficulty: { tr: "Başlangıç-Orta", en: "Beginner-Intermediate" },
      output: {
        tr: "Direnç, LED, kondansatör ve transistörle basit devre kurup çalışma notu çıkarma.",
        en: "Build a basic circuit with resistor, LED, capacitor, transistor and write notes about how it works.",
      },
    },
    strengths: {
      tr: ["Güçlü mühendislik temeli verir", "Donanım ve haberleşmeye açılır", "Gömülü sistemleri daha iyi anlamayı sağlar"],
      en: ["Gives a strong engineering base", "Opens into hardware and communication", "Helps understand embedded systems better"],
    },
    cautions: {
      tr: ["Matematik/fizik emeği ister", "Sonuç bazen yavaş gelir", "Lab ve ölçüm dikkat ister"],
      en: ["Requires math/physics effort", "Results may come slowly", "Lab and measurement require care"],
    },
  },
];

export const questions = [
  {
    id: "q1",
    text: {
      tr: "Bir fikri kodla çalışan bir ürüne çevirmek beni heyecanlandırır.",
      en: "Turning an idea into a working product with code excites me.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q2",
    text: {
      tr: "Bir sistemin neden güvensiz olduğunu anlamak ilgimi çeker.",
      en: "Understanding why a system is insecure interests me.",
    },
    weights: { software: 1, security: 3, hardware: 1, electronics: 0 },
  },
  {
    id: "q3",
    text: {
      tr: "Kodun bir sensör, LED, motor veya cihaz üzerinde sonuç üretmesi hoşuma gider.",
      en: "I like seeing code affect a sensor, LED, motor, or device.",
    },
    weights: { software: 1, security: 0, hardware: 3, electronics: 2 },
  },
  {
    id: "q4",
    text: {
      tr: "Devrelerin ve sinyallerin nasıl çalıştığını merak ederim.",
      en: "I am curious about how circuits and signals work.",
    },
    weights: { software: 0, security: 0, hardware: 2, electronics: 3 },
  },
  {
    id: "q5",
    text: {
      tr: "Uzun süre hata ayıklamak beni hemen soğutmaz.",
      en: "Long debugging sessions do not discourage me quickly.",
    },
    weights: { software: 3, security: 2, hardware: 2, electronics: 1 },
  },
  {
    id: "q6",
    text: {
      tr: "Linux, ağ, IP, port ve log gibi kavramları öğrenmek isterim.",
      en: "I want to learn concepts like Linux, networks, IP, ports, and logs.",
    },
    weights: { software: 1, security: 3, hardware: 1, electronics: 0 },
  },
  {
    id: "q7",
    text: {
      tr: "Matematik ve fizik ağırlığı beni korkutmuyor.",
      en: "Math and physics intensity does not scare me.",
    },
    weights: { software: 1, security: 1, hardware: 2, electronics: 3 },
  },
  {
    id: "q8",
    text: {
      tr: "Kullanıcıya faydalı bir arayüz veya uygulama yapmak isterim.",
      en: "I want to build useful interfaces or apps for people.",
    },
    weights: { software: 3, security: 0, hardware: 0, electronics: 0 },
  },
  {
    id: "q9",
    text: {
      tr: "Detaylı doküman okuyup not almak bana uygun olabilir.",
      en: "Reading detailed documentation and taking notes may suit me.",
    },
    weights: { software: 2, security: 3, hardware: 1, electronics: 2 },
  },
  {
    id: "q10",
    text: {
      tr: "Kablo, kart, sensör ve fiziksel parçalarla uğraşmak isterim.",
      en: "I want to work with wires, boards, sensors, and physical parts.",
    },
    weights: { software: 0, security: 0, hardware: 3, electronics: 3 },
  },
  {
    id: "q11",
    text: {
      tr: "Bir problemi küçük adımlara bölmek benim için doğal.",
      en: "Breaking a problem into small steps feels natural to me.",
    },
    weights: { software: 3, security: 2, hardware: 2, electronics: 2 },
  },
  {
    id: "q12",
    text: {
      tr: "Etik sınırlara dikkat ederek güvenlik labları çözmek isterim.",
      en: "I want to solve security labs while respecting ethical boundaries.",
    },
    weights: { software: 0, security: 3, hardware: 0, electronics: 0 },
  },
  {
    id: "q13",
    text: {
      tr: "Daha düşük seviyeli C/C++ ve cihaz mantığı ilgimi çeker.",
      en: "Lower-level C/C++ and device logic interest me.",
    },
    weights: { software: 1, security: 1, hardware: 3, electronics: 2 },
  },
  {
    id: "q14",
    text: {
      tr: "Sinyal, haberleşme, elektrik ve ölçüm konuları bana yakın geliyor.",
      en: "Signals, communication, electricity, and measurement feel close to me.",
    },
    weights: { software: 0, security: 1, hardware: 1, electronics: 3 },
  },
  {
    id: "q15",
    text: {
      tr: "Portfolyo için kendi projelerimi yayınlamak isterim.",
      en: "I want to publish my own projects for a portfolio.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q16",
    text: {
      tr: "Bir zafiyeti bulup sade biçimde raporlamak ilgimi çeker.",
      en: "Finding a vulnerability and reporting it clearly interests me.",
    },
    weights: { software: 1, security: 3, hardware: 0, electronics: 0 },
  },
  {
    id: "q17",
    text: {
      tr: "Fiziksel prototipte deneme-yanılma yapmak bana keyifli gelir.",
      en: "Trial and error on a physical prototype sounds enjoyable.",
    },
    weights: { software: 0, security: 0, hardware: 3, electronics: 2 },
  },
  {
    id: "q18",
    text: {
      tr: "Teorik konuları sabırla çalışıp derinlemesine anlamaya istekliyim.",
      en: "I am willing to study theory patiently and understand it deeply.",
    },
    weights: { software: 1, security: 1, hardware: 2, electronics: 3 },
  },
  {
    id: "q19",
    text: {
      tr: "Takımla uygulama geliştirmek ve geri bildirim almak isterim.",
      en: "I want to build apps with a team and get feedback.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q20",
    text: {
      tr: "Sistemleri hem yazılım hem donanım tarafıyla anlamak isterim.",
      en: "I want to understand systems from both software and hardware sides.",
    },
    weights: { software: 1, security: 1, hardware: 3, electronics: 2 },
  },
];

export const t = {
  tr: {
    appName: "Bölüm Pusulası",
    nav: {
      landing: "Ana Sayfa",
      home: "Genel Bakış",
      test: "Alan Testi",
      results: "Sonuç",
      guide: "Alan Rehberi",
      projects: "Mini Görevler",
      compare: "Üniversite",
      shortlist: "Tercihler",
      journal: "Günlük",
      resources: "Kaynaklar",
      knowledge: "Atölye Notları",
      workshop: "Atölye",
      pusula: "Bölüm Pusulası",
      project2: "Proje 2",
      project2Build: "Yapım Süreci",
      project2ScopeRecon: "Kapsam/Kesif",
      project2ExploitLab: "Exploit Lab",
      project2DnsExplorer: "DNS",
      project2WafSignals: "WAF",
      project2HostMap: "Host/VPS",
      project2TechFingerprint: "Teknoloji İzi",
      project2ExtensionAudit: "Eklenti İzinleri",
      project2FridaWorkbench: "Frida",
      project2WebQDashboard: "WebQ",
      project: "Proje",
      buildProcess: "Yapım Süreci",
      instructor: "Eğitmen",
      homeworks: "Ödevler",
      glossary: "Terimler Sözlüğü",
      feedback: "Geri Bildirim",
    },
    common: {
      startTest: "Teste Başla",
      inspectFields: "Alanları İncele",
      compareUniversities: "Üniversiteleri Karşılaştır",
      save: "Kaydet",
      add: "Ekle",
      delete: "Sil",
      clear: "Temizle",
      reset: "Yeniden Başla",
      close: "Kapat",
      next: "İleri",
      back: "Geri",
      finish: "Testi Bitir",
      empty: "Henüz veri yok.",
      themeLight: "Gündüz",
      themeDark: "Gece",
      language: "Dil",
      viewMode: "Görünüm modu",
      compactMode: "Kompakt",
      visualizedMode: "Görsel",
      official: "Resmi kaynak",
      open: "Aç",
      yourData: "Verilerin bu tarayıcıda saklanır.",
      footerCreditPrefix: "Derleyen, düzenleyen ve uygulayan",
    },
    home: {
      eyebrow: "Statik karar aracı",
      title: "Bölüm seçimi kafanı karıştırıyorsa buradan başla.",
      subtitle:
        "Yazılım, siber güvenlik, donanım/gömülü sistemler ve elektronik arasında karar vermek için test, mini görevler, günlük ve tercih listesi tek yerde.",
      quickStats: ["9 sayfa", "TR/EN", "Gece/gündüz", "Backend yok"],
      processTitle: "Karar süreci",
      process: ["Kısa testi çöz", "Sonucunu incele", "Mini görev dene", "Üniversiteleri karşılaştır", "Karar cümleni yaz"],
      continueResult: "Kayıtlı sonuç var",
      noResult: "Henüz test sonucu yok",
    },
    test: {
      title: "Alan Testi",
      subtitle: "Her cümlenin sana ne kadar uyduğunu seç. Sonuç kesin hüküm vermez; önce hangi alanları denemen gerektiğini gösterir.",
      scale: ["Hiç uymuyor", "Az uyuyor", "Kararsızım", "Uyuyor", "Çok uyuyor"],
      answered: "cevaplandı",
      needAnswer: "Devam etmek için bir seçenek seç.",
    },
    results: {
      title: "Sonuç Analizi",
      subtitle: "Skorlar ilgi düzeyini ve deneme önceliğini gösterir. En yüksek iki alanı önce denemen mantıklı.",
      noResultTitle: "Sonucu görmek için önce testi bitir.",
      topFields: "En yakın alanlar",
      strengths: "Güçlü taraflar",
      cautions: "Dikkat noktalar",
      plan: "3 günlük deneme planı",
      day1: "Gün 1: temel kavramları öğren ve kısa notlar al.",
      day2: "Gün 2: mini görevin ilk çalışan parçasını yap.",
      day3: "Gün 3: sonucu yaz; keyif, sabır ve merak açısından değerlendir.",
    },
    guide: {
      title: "Alan Rehberi",
      subtitle: "Her alanın günlük çalışma tarzını, kimlere uygun olduğunu ve hangi bölümlere bağlandığını gösterir.",
      likes: "Kimler sever?",
      struggles: "Kimler zorlanır?",
      departments: "İlgili bölümler",
      daily: "Günlük iş tarzı",
    },
    projects: {
      title: "Mini Proje Görevleri",
      subtitle: "İlgi alanı sadece düşünerek değil, küçük deneylerle netleşir. Her alan için 3 günlük pratik görev.",
      time: "Süre",
      difficulty: "Zorluk",
      output: "Beklenen çıktı",
      ethics: "Güvenlik görevlerinde yalnızca yasal eğitim laboratuvarlarını kullan. İzinsiz deneme yapma.",
    },
    compare: {
      title: "Üniversite Karşılaştırma",
      subtitle: "Aday bölümleri aynı kriterlerle yaz. Bu ilk sürümde veriler tarayıcındaki localStorage alanında tutulur.",
      university: "Üniversite",
      program: "Bölüm",
      city: "Şehir",
      rank: "Başarı sırası",
      language: "Dil",
      campus: "Kampüs",
      founded: "Kuruluş",
      curriculum: "Ders planı puanı",
      labs: "Laboratuvar / kulüp / staj notu",
      notes: "Notlar",
      addToShortlist: "Tercihe ekle",
      saved: "Kayıtlı karşılaştırmalar",
    },
    shortlist: {
      title: "Tercih Listesi",
      subtitle: "En güçlü aday bölümleri sırala, neden istediğini yaz ve listeyi sade tut.",
      university: "Üniversite",
      program: "Bölüm",
      reason: "Neden listede?",
      priority: "Öncelik",
      saved: "Kısa liste",
      moveUp: "Yukarı al",
      moveDown: "Aşağı al",
    },
    journal: {
      title: "Karar Günlüğü",
      subtitle: "Kararını yazılı hale getir. Belirsizlik azalır; atman gereken sonraki adım daha net görünür.",
      current: "Şu an hangi alana daha yakınım?",
      why: "Neden?",
      excited: "Beni en çok ne heyecanlandırıyor?",
      worried: "Beni en çok ne kaygılandırıyor?",
      experiment: "Bu hafta hangi mini denemeyi yapacağım?",
      finalSentence: "Son karar cümlem",
      summary: "Okunabilir özet",
    },
    resources: {
      title: "Kaynaklar",
      subtitle: "Tercih için son kontrolü resmi kaynaklardan yap. Bu site karar sürecini kolaylaştırır; resmi kılavuzların yerine geçmez.",
      officialTitle: "Resmi kaynaklar",
      checklistTitle: "Bölüm araştırma kontrol listesi",
      talkTitle: "Öğrenci/mezun soruları",
      safetyTitle: "Güvenli öğrenme notu",
      safety: "Siber güvenlik pratiği yalnızca izinli laboratuvarlarda ve eğitim ortamlarında yapılmalı.",
    },
    knowledge: {
      title: "Atölye Notları",
      subtitle: "Atölye boyunca işlenen konuların etkileşimli özeti. Konuları sırayla incele, öğrendiklerini işaretle.",
      progressLabel: "İlerleme",
      topicsLabel: "konu öğrenildi",
      markLearned: "Öğrendim olarak işaretle",
      learned: "Öğrenildi",
      unmark: "İşareti kaldır",
      previous: "Önceki konu",
      next: "Sonraki konu",
      randomReview: "Rastgele tekrar",
      resetProgress: "İlerlemeyi sıfırla",
      allDone: "Tebrikler, tüm konuları işaretledin!",
      flipHint: "Kart özetini görmek için tıkla",
      quickReview: "Hızlı tekrar kartı",
      dayAll: "Tüm Günler",
      day1: "1. Gün",
      day2: "2. Gün",
      placeholderBadge: "Yakında",
      placeholderNote: "Bu konu henüz canlı anlatımla doldurulmadı. Aşağıda o oturumda işlenecek başlık taslağı var.",
      tocTitle: "İşlenecek Başlıklar",
      contribute: "Repo'ya Katkı Yap",
    },
    landing: {
      eyebrow: "Atölye Ana Sayfası",
      title: "Bilgisayar biliminin gerçek dünyaya dönüştüğü uygulamalı bir AI atölyesi.",
      subtitle:
        "Bu atölyede önce bilgisayar donanımı, yazılım, veri ve güvenlik temellerini akademik bir zeminde kurduk. Ardından yazılım geliştirme, mimari düşünme, prompt engineering ve sistem güvenliği konularına derinleştik. Son adımda her kavramı gerçek dünyadaki karşılığına dokunan pratik uygulamalara dönüştürdük: test edilebilir, doğrulanabilir ve tekrar üretilebilir çıktılar.",
      topicTags: [
        "Bilgi İşlemsel Düşünme",
        "Donanım Okuryazarlığı",
        "Yazılım Mimarisi",
        "Veri Güvenliği",
        "Güvenli SDLC",
        "Prompt Engineering",
        "Agentic AI Uygulaması",
        "Deterministik Test",
      ],
      ctaNotes: "Not Atlasını Aç",
      ctaPusula: "Bölüm Pusulası'nı Keşfet",
      ctaProcess: "Yapım Sürecini Gör",
      ctaInstructor: "Eğitmeni Tanı",
      notesTitle: "Bilgiden Sisteme: Atölye Haritası",
      notesSubtitle:
        "Not kartları ana sayfada kalabalık oluşturmuyor. Konu atlasını modal içinde açabilir, istediğin notun detayına tek adımda geçebilirsin.",
      notesSeeAll: "Not atlasını aç",
      notesModalCta: "Konu atlasını modalda incele",
      notesModalEyebrow: "Atölye Bilgi Atlası",
      notesModalTitle: "Atölye Notları Atlası",
      arcEyebrow: "Akademik Yolculuk",
      arcTitle: "Temel bilimden gerçek sisteme, gerçek sistemden güvenli ürüne.",
      arcSubtitle:
        "Dersin omurgası yalnızca 'AI ile kod yazmak' değil. Bilgisayarın fiziksel gerçekliğinden yazılım mimarisine, verinin korunmasından güvenli ürün tasarımına uzanan bütünlüklü bir mühendislik çizgisi.",
      learningArc: [
        {
          title: "Bilgisayar Bilimi Temeli",
          body: "Donanım, işletim sistemi, veri, ağ ve yazılım kavramlarını aynı sistemin birbirine bağlı katmanları olarak inceledik.",
        },
        {
          title: "Yazılım Geliştirme Derinliği",
          body: "Git, repo kültürü, dokümantasyon, mimari kararlar, test ve agent çıktısı denetimini gerçek bir proje üzerinde uyguladık.",
        },
        {
          title: "Güvenlik ve Savunma Zihniyeti",
          body: "Web, DNS, WAF, host/VPS, tarayıcı eklentisi riski, Frida ve WebQ konularını izinli ve etik sınırlar içinde ele aldık.",
        },
        {
          title: "Agentic AI Üretim Hattı",
          body: "Prompt engineering, planlama, araç kullanan ajanlar ve insan denetimiyle hızlı ama kontrollü bir uygulama hattı kurduk.",
        },
      ],
      accelerationEyebrow: "Uygulamalı AI Mühendisliği",
      accelerationTitle: "100x+ hız, testli doğruluk ve mimari disiplin aynı hatta.",
      accelerationShort: "Agentic AI ile olağan geliştirme ritminin çok ötesinde; yine de denetimli, ölçülebilir ve testlenebilir üretim.",
      accelerationBody:
        "Amaç hızlı bir demo çıkarmak değil; gerçek dünya örneklerini modelleyen, ölçülebilir, tekrar üretilebilir ve doğrulanabilir uygulamalar geliştirmek. Agentic AI burada yalnızca kod yazan bir asistan değil; prompt, mimari, test ve güvenlik reflekslerini birlikte çalıştıran bir üretim orkestrasyonu.",
      accelerationStats: [
        { value: "100x+", label: "Üretim ivmesi", body: "Normal geliştirme ritmine göre çok daha hızlı prototip; yine de commit, build ve test disipliniyle." },
        { value: "0-100", label: "Mimari hat", body: "Fikirden yol haritasına, component'ten doğrulanmış ekrana kadar izlenebilir uygulama." },
        { value: "TR/EN", label: "Akademik erişim", body: "Konu anlatımı, arayüz ve notlar iki dilde tasarlandı; kavram kaybı en aza indirildi." },
      ],
      pusulaTitle: "Proje: Bölüm Pusulası",
      pusulaSubtitle:
        "1. gün projesi: Agentic AI araçlarıyla (Claude Code, Codex) baştan sona kodladığımız gerçek bir web uygulaması. Üniversite bölüm kararı için test, rehber, karşılaştırma ve karar günlüğü sunar.",
      pusulaCta: "Projeyi Aç",
      processTitle: "Nasıl Yapıldı?",
      processSubtitle:
        "Bölüm Pusulası tek seferde oluşmadı; gerçek commit'lerle adım adım büyüdü. Yapım sürecini inceleyerek Agentic AI ile bir projenin nasıl geliştiğini görebilirsin.",
      processCta: "Yapım Sürecini Aç",
    },
    instructor: {
      title: "Eğitmen",
      subtitle: "Bu atölyeyi hazırlayan ve sunan eğitmen hakkında kısa bilgi.",
      roleLabel: "İstinye Üniversitesi Meslek Yüksekokulu - Akademik Kadro",
      bio: "Bu atölyede bilgisayar bölümü öğrencilerine yazılım geliştirme süreci, Git/GitHub pratikleri, Agentic AI araçlarıyla çalışma ve siber güvenlik için gerekli temel düşünme biçimi anlatıldı.",
      linksTitle: "Bağlantılar",
      academicProfile: "Akademik Profil",
      github: "GitHub",
      linkedin: "LinkedIn",
      internshipTitle: "Yaz Araştırma Stajı",
      internshipDesc: "İstinye Üniversitesi'nin yaz araştırma stajı programı hakkında güncel bilgi ve başvuru için resmi sayfayı ziyaret et.",
      internshipCta: "Programı İncele",
      backToKnowledge: "Atölye Notlarına Dön",
    },
    buildProcess: {
      title: "Yapım Süreci",
      subtitle:
        "Bölüm Pusulası tek büyük adımda değil, gerçek commit'lerle ilerledi. Bu zaman çizelgesi, Agentic AI ile bir projenin nasıl adım adım büyüdüğünü gösterir.",
      commitLabel: "Commit",
      filesTitle: "Neler değişti",
      lessonTitle: "Buradan çıkan ders",
      liveBadge: "Şu an devam ediyor",
      liveNote: "Atölye ve site canlı oturumlarda gelişmeye devam ediyor; bu zaman çizelgesi de sürekli büyüyor.",
      relatedNote: "İlgili not",
    },
    project2: {
      name: "Proje 2: Güvenlik Keşif Laboratuvarı",
      kicker: "2. Gün Projesi",
      day2Badge: "2. gün notları",
      buildTitle: "Proje 2 Yapım Süreci",
      buildSubtitle:
        "Bölüm Pusulası 1. gün projesi olarak kalır. Bu ikinci proje, 2. gün güvenlik notlarını eğitim odaklı, izinli ve savunma merkezli arayüzlere dönüştürür.",
      buildIntro:
        "Bu sayfa Proje 2'nin nasıl büyüyeceğini gösterir: önce sayfa kabukları, sonra her not için güvenli biçimde simüle edilen özellikler.",
      placeholderBadge: "Taslak",
      componentShell: "Bu sayfa henüz çalışan bir araç değil; planlanan React component kabuğunu ve kullanıcı deneyimini açıklar.",
      functionalityTitle: "Sayfa / component işlevi",
      placeholderBlocks: [
        { title: "Girdi", body: "Kullanıcı izinli hedef/kapsam veya eğitim senaryosu girer." },
        { title: "Süreç", body: "Arayüz, nottaki kavramları zararsız ve adım adım bir model olarak gösterir." },
        { title: "Çıktı", body: "Sonuç; savunma odaklı rapor, kontrol listesi veya öğrenme özeti olur." },
      ],
      relatedNotesTitle: "Bu sayfanın not bağlantısı",
      relatedNotesBody: "Butona bastığında ilgili 2. gün notu modal içinde açılır; sayfadan ayrılman gerekmez.",
      relatedNotesButton: "İlgili notlar",
      openRelatedNotes: "İlgili notları modalda aç",
      modalEyebrow: "Atölye Notları",
      modalTitle: "İlgili 2. Gün Notları",
    },
    homeworks: {
      title: "Ödevler",
      subtitle: "Atölyede verilen ödevler ve her biri için adım adım katkı rehberi.",
      numberLabel: "Ödev",
    },
    glossary: {
      title: "Terimler Sözlüğü",
      subtitle: "Atölyede işlenen tüm terimler, kısa açıklamalar ve gerçek dünya örnekleriyle.",
      exampleLabel: "Gerçek Dünya Örneği",
      pendingBadge: "Katkı Bekliyor",
      pendingNote: "Bu terimin örneği henüz eklenmedi; Ödev 3'te bunu sen ekleyebilirsin.",
    },
    feedback: {
      title: "Geri Bildirim",
      subtitle: "Atölyeye katılan öğrencilerin gerçek görüşleri.",
      emptyTitle: "Henüz geri bildirim yok.",
      emptyBody: "Bu atölyeye katıldın mı? İlk geri bildirimi ekleyen sen ol.",
      ctaBody: "Geri bildirim eklemek, Git/GitHub katkı sürecini gerçek hayatta uygulamanın en iyi yollarından biridir. Adım adım rehber Ödev 2'de.",
      ctaButton: "Ödev 2'yi Aç",
    },
  },
  en: {
    appName: "Path Compass",
    nav: {
      landing: "Home",
      home: "Overview",
      test: "Field Test",
      results: "Results",
      guide: "Field Guide",
      projects: "Mini Tasks",
      compare: "University",
      shortlist: "Shortlist",
      journal: "Journal",
      resources: "Resources",
      knowledge: "Workshop Notes",
      workshop: "Workshop",
      pusula: "Path Compass",
      project2: "Project 2",
      project2Build: "Build Process",
      project2ScopeRecon: "Scope/Recon",
      project2ExploitLab: "Exploit Lab",
      project2DnsExplorer: "DNS",
      project2WafSignals: "WAF",
      project2HostMap: "Host/VPS",
      project2TechFingerprint: "Tech Fingerprint",
      project2ExtensionAudit: "Extension Audit",
      project2FridaWorkbench: "Frida",
      project2WebQDashboard: "WebQ",
      project: "Project",
      buildProcess: "Build Process",
      instructor: "Instructor",
      homeworks: "Homeworks",
      glossary: "Glossary",
      feedback: "Feedback",
    },
    common: {
      startTest: "Start Test",
      inspectFields: "Explore Fields",
      compareUniversities: "Compare Universities",
      save: "Save",
      add: "Add",
      delete: "Delete",
      clear: "Clear",
      reset: "Restart",
      close: "Close",
      next: "Next",
      back: "Back",
      finish: "Finish Test",
      empty: "No data yet.",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      viewMode: "View mode",
      compactMode: "Compact",
      visualizedMode: "Visualized",
      official: "Official source",
      open: "Open",
      yourData: "Your data stays in this browser.",
      footerCreditPrefix: "Collected, organized, and implemented by",
    },
    home: {
      eyebrow: "Static decision tool",
      title: "Not sure which university path fits you? Start here.",
      subtitle:
        "Use a test, mini tasks, a journal, and a shortlist to compare software, cybersecurity, hardware/embedded, and electronics.",
      quickStats: ["9 pages", "TR/EN", "Light/dark", "No backend"],
      processTitle: "Decision process",
      process: ["Take the short test", "Review your result", "Try a mini task", "Compare universities", "Write your decision sentence"],
      continueResult: "Saved result found",
      noResult: "No test result yet",
    },
    test: {
      title: "Field Test",
      subtitle: "Choose how much each sentence fits you. The result is not a final verdict; it shows which fields you should try first.",
      scale: ["Not at all", "A little", "Not sure", "Fits", "Fits strongly"],
      answered: "answered",
      needAnswer: "Pick an option to continue.",
    },
    results: {
      title: "Result Analysis",
      subtitle: "Scores show interest and experiment priority. Try the top two fields first.",
      noResultTitle: "Finish the test to see your result.",
      topFields: "Closest fields",
      strengths: "Strengths",
      cautions: "Watch points",
      plan: "3-day experiment plan",
      day1: "Day 1: learn the core concepts and take short notes.",
      day2: "Day 2: build the first working piece of the mini task.",
      day3: "Day 3: write what happened and score fun/patience/curiosity.",
    },
    guide: {
      title: "Field Guide",
      subtitle: "Daily work style, fit, difficulty, and related university majors for each field.",
      likes: "Who may like it?",
      struggles: "Who may struggle?",
      departments: "Related majors",
      daily: "Daily work style",
    },
    projects: {
      title: "Mini Project Tasks",
      subtitle: "You discover interest by trying, not only by thinking. Each field has a 3-day practical task.",
      time: "Time",
      difficulty: "Difficulty",
      output: "Expected output",
      ethics: "For security tasks, use only legal training labs. Do not test systems without permission.",
    },
    compare: {
      title: "University Comparison",
      subtitle: "Write candidate programs with the same criteria. In the first version, data is stored in your browser with localStorage.",
      university: "University",
      program: "Program",
      city: "City",
      rank: "Admission rank",
      language: "Language",
      campus: "Campus",
      founded: "Founded",
      curriculum: "Curriculum score",
      labs: "Lab / club / internship notes",
      notes: "Notes",
      addToShortlist: "Add to shortlist",
      saved: "Saved comparisons",
      featuredTitle: "Verified Istanbul universities",
      featuredSubtitle: "Ready-to-use profiles collected from official university and YOK Atlas pages.",
      featuredAction: "Add to comparison",
      officialSite: "Official site",
      profileBadge: "Verified profile",
    },
    shortlist: {
      title: "Shortlist",
      subtitle: "Rank your strongest candidate programs, write why they matter, and keep the list focused.",
      university: "University",
      program: "Program",
      reason: "Why is it listed?",
      priority: "Priority",
      saved: "Shortlist",
      moveUp: "Move up",
      moveDown: "Move down",
    },
    journal: {
      title: "Decision Journal",
      subtitle: "Put your thinking into words. Uncertainty shrinks and the next step becomes clearer.",
      current: "Which field feels closest right now?",
      why: "Why?",
      excited: "What excites me most?",
      worried: "What worries me most?",
      experiment: "Which mini experiment will I try this week?",
      finalSentence: "Final decision sentence",
      summary: "Readable summary",
    },
    resources: {
      title: "Resources",
      subtitle: "Use official sources for the final check. This site helps your decision process; it does not replace official guides.",
      officialTitle: "Official sources",
      checklistTitle: "Program research checklist",
      talkTitle: "Questions for students/graduates",
      safetyTitle: "Safe learning note",
      safety: "Cybersecurity practice should only happen in permitted labs and training environments.",
    },
    knowledge: {
      title: "Workshop Notes",
      subtitle: "An interactive summary of the topics covered in the workshop. Go through them in order and mark what you've learned.",
      progressLabel: "Progress",
      topicsLabel: "topics learned",
      markLearned: "Mark as learned",
      learned: "Learned",
      unmark: "Unmark",
      previous: "Previous topic",
      next: "Next topic",
      randomReview: "Random review",
      resetProgress: "Reset progress",
      allDone: "Nice work, you've marked every topic!",
      flipHint: "Click the card to see the summary",
      quickReview: "Quick review card",
      dayAll: "All Days",
      day1: "Day 1",
      day2: "Day 2",
      placeholderBadge: "Coming soon",
      placeholderNote: "This topic hasn't been taught live yet. Here's the draft outline for that session.",
      tocTitle: "Topics to Cover",
      contribute: "Contribute on the Repo",
    },
    landing: {
      eyebrow: "Workshop Home",
      title: "An applied AI workshop where computer science becomes real software.",
      subtitle:
        "This workshop was not only about building software with agentic AI. We began with the foundations of computer hardware, software, data, and security; then moved deeper into software development, architecture, prompt engineering, and system security. Finally, we translated each concept into practical real-world implementations: testable, verifiable, and reproducible outputs.",
      topicTags: [
        "Computational Thinking",
        "Hardware Literacy",
        "Software Architecture",
        "Data Security",
        "Secure SDLC",
        "Prompt Engineering",
        "Agentic Implementation",
        "Deterministic Testing",
      ],
      ctaNotes: "Open the Notes Atlas",
      ctaPusula: "Explore Path Compass",
      ctaProcess: "See the Build Process",
      ctaInstructor: "Meet the Instructor",
      notesTitle: "From Knowledge to Systems: Workshop Map",
      notesSubtitle:
        "The note cards no longer crowd the homepage. Open the topic atlas in a modal and jump into any detailed note from there.",
      notesSeeAll: "Open notes atlas",
      notesModalCta: "Explore the topic atlas in a modal",
      notesModalEyebrow: "Workshop Knowledge Atlas",
      notesModalTitle: "Workshop Notes Atlas",
      arcEyebrow: "Academic Journey",
      arcTitle: "From foundations to real systems, from real systems to secure products.",
      arcSubtitle:
        "The spine of the course is not just 'coding with AI'. It is a complete engineering line: from the physical reality of computers to software architecture, from data protection to secure product thinking and tested implementation.",
      learningArc: [
        {
          title: "Computer Science Grounding",
          body: "We studied hardware, operating systems, data, networks, and software as connected layers of one system.",
        },
        {
          title: "Software Development Depth",
          body: "We practiced Git, repository culture, documentation, architecture decisions, testing, and agent output review inside a real project.",
        },
        {
          title: "Security and Defense Mindset",
          body: "We covered web, DNS, WAF, host/VPS, browser extension risk, Frida, and WebQ within authorized and ethical boundaries.",
        },
        {
          title: "Agentic AI Production Line",
          body: "We combined prompt engineering, planning, tool-using agents, and human review into fast but controlled implementation.",
        },
      ],
      accelerationEyebrow: "Applied AI Engineering",
      accelerationTitle: "100x+ speed, tested accuracy, and architectural discipline on the same line.",
      accelerationShort: "Agentic AI moves far beyond the ordinary development rhythm while staying reviewed, tested, and measurable.",
      accelerationBody:
        "The goal is not a quick demo. The goal is implementation that models real-world cases and can be measured, reproduced, verified, and improved. Here, agentic AI is not merely a code assistant; it is production orchestration across prompts, architecture, tests, and security reflexes.",
      accelerationStats: [
        { value: "100x+", label: "Production acceleration", body: "Much faster prototyping than the usual development rhythm, still shaped by commits, builds, and tests." },
        { value: "0-100", label: "Architecture line", body: "Traceable implementation from idea to roadmap, from component to verified screen." },
        { value: "TR/EN", label: "Academic access", body: "Concepts, UI, and notes are designed bilingually to minimize meaning loss." },
      ],
      pusulaTitle: "Project: Path Compass",
      pusulaSubtitle:
        "Day 1 project: a real web app built end-to-end in this workshop with agentic AI tools (Claude Code, Codex): a test, guide, comparison tool, and decision journal for choosing a university major.",
      pusulaCta: "Open the Project",
      processTitle: "How Was It Built?",
      processSubtitle:
        "Path Compass did not appear all at once; it grew commit by commit. Open the Build Process to see how a project evolves with agentic AI.",
      processCta: "Open the Build Process",
    },
    instructor: {
      title: "Instructor",
      subtitle: "A short introduction to the instructor who prepared and delivered this workshop.",
      roleLabel: "Istinye University Vocational School - Academic Staff",
      bio: "In this workshop, computer department students studied the software development process, Git/GitHub practices, working with agentic AI tools, and the core reasoning needed for cybersecurity.",
      linksTitle: "Links",
      academicProfile: "Academic Profile",
      github: "GitHub",
      linkedin: "LinkedIn",
      internshipTitle: "Summer Research Internship",
      internshipDesc: "Visit the official page for up-to-date information and applications for Istinye University's summer research internship program.",
      internshipCta: "View the Program",
      backToKnowledge: "Back to Workshop Notes",
    },
    buildProcess: {
      title: "Build Process",
      subtitle:
        "Path Compass grew through real commits, not one giant leap. This timeline shows how a project grows step by step with agentic AI.",
      commitLabel: "Commit",
      filesTitle: "What changed",
      lessonTitle: "The takeaway",
      liveBadge: "In progress right now",
      liveNote: "The workshop and this site keep evolving in live sessions; this timeline keeps growing.",
      relatedNote: "Related note",
    },
    project2: {
      name: "Project 2: Security Recon Lab",
      kicker: "Day 2 Project",
      day2Badge: "Day 2 notes",
      buildTitle: "Project 2 Build Process",
      buildSubtitle:
        "Path Compass remains the Day 1 project. This second project turns the Day 2 security notes into educational, authorized, defense-centered interfaces.",
      buildIntro:
        "This page shows how Project 2 will grow: page shells first, then safely simulated features for each note.",
      placeholderBadge: "Draft",
      componentShell: "This page is not a working tool yet; it explains the planned React component shell and user experience.",
      functionalityTitle: "Page / component functionality",
      placeholderBlocks: [
        { title: "Input", body: "The user enters an authorized target/scope or a learning scenario." },
        { title: "Process", body: "The UI presents the note concepts as harmless, step-by-step models." },
        { title: "Output", body: "The result becomes a defense-focused report, checklist, or learning summary." },
      ],
      relatedNotesTitle: "Note connection for this page",
      relatedNotesBody: "Press the button to open the related Day 2 note in a modal without leaving the page.",
      relatedNotesButton: "Related notes",
      openRelatedNotes: "Open related notes in modal",
      modalEyebrow: "Workshop Notes",
      modalTitle: "Related Day 2 Notes",
    },
    homeworks: {
      title: "Homeworks",
      subtitle: "The homeworks assigned in this workshop, each with a step-by-step contribution guide.",
      numberLabel: "Homework",
    },
    glossary: {
      title: "Glossary",
      subtitle: "Every term covered in the workshop, with a short description and a real-world example.",
      exampleLabel: "Real-World Example",
      pendingBadge: "Awaiting Contribution",
      pendingNote: "This term's example hasn't been added yet — you can add it in Homework 3.",
    },
    feedback: {
      title: "Feedback",
      subtitle: "Real feedback from students who joined this workshop.",
      emptyTitle: "No feedback yet.",
      emptyBody: "Did you join this workshop? Be the first to add your feedback.",
      ctaBody: "Adding your feedback is one of the best ways to practice the Git/GitHub contribution flow in a real setting. The step-by-step guide is in Homework 2.",
      ctaButton: "Open Homework 2",
    },
  },
};

export const resources = [
  {
    title: "YOK Atlas",
    href: "https://yokatlas.yok.gov.tr/",
    desc: {
      tr: "Program, basari sirasi, kontenjan ve universite arastirmasi icin resmi kaynak.",
      en: "Official source for program, ranking, quota, and university research.",
    },
  },
  {
    title: "OSYM",
    href: "https://www.osym.gov.tr/",
    desc: {
      tr: "Sinav, kilavuz, duyuru ve nihai tercih kosullari icin resmi kaynak.",
      en: "Official source for exams, guides, announcements, and final preference rules.",
    },
  },
  {
    title: "OSYM 2026-YKS Kilavuzu",
    href: "https://www.osym.gov.tr/TR%2C33851/2026-yuksekogretim-kurumlari-sinavi-yks-kilavuzu.html",
    desc: {
      tr: "2026 YKS sureci icin kilavuz ve ilgili dokumanlar.",
      en: "Guide and related documents for the 2026 YKS process.",
    },
  },
];

export const featuredUniversities = [
  {
    id: "boun",
    university: "Boğaziçi Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Bebek / Rumeli Hisarı",
    founded: "1863 kökler, 1971 resmi ad",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma odaklı, uluslararası ve güçlü mühendislik geleneği",
    website: "https://www.boun.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.boun.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=102210277" },
    ],
    compare: {
      university: "Boğaziçi Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Bebek / Rumeli Hisarı, araştırma odaklı profil",
      labs: "Güçlü akademik kadro ve uluslararası eğitim dili",
      notes: "Kökleri 1863'e dayanan, resmi adı 1971'de alınan üniversite.",
    },
  },
  {
    id: "itu",
    university: "İstanbul Teknik Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Ayazağa, Gümüşsuyu, Maçka, Taşkışla, Tuzla",
    founded: "1773",
    language: "İngilizce / %30 İngilizce programlar",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Mühendislik, araştırma ve teknik altyapı",
    website: "https://www.itu.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.itu.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=105510608" },
    ],
    compare: {
      university: "İstanbul Teknik Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "13 fakülte, 99 lisans programı",
      labs: "Beş kampüs, güçlü laboratuvar ve araştırma altyapısı",
      notes: "1773'e uzanan köklü teknik üniversite.",
    },
  },
  {
    id: "istanbul",
    university: "İstanbul Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Beyazıt / Fatih ve diğer yerleşkeler",
    founded: "1933",
    language: "Türkçe / seçili programlarda İngilizce",
    program: "Yapay Zeka ve Veri Mühendisliği (İngilizce)",
    focus: "Tarihsel kökler, geniş akademik yapı, merkez kampüs",
    website: "https://www.istanbul.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.istanbul.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=105690984" },
    ],
    compare: {
      university: "İstanbul Üniversitesi",
      program: "Yapay Zeka ve Veri Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Merkez kampüs ve geniş akademik fakülte yapısı",
      labs: "Bilgisayar ve Bilişim Teknolojileri Fakültesi üzerinden örnek program",
      notes: "1933 Üniversite Reformu ile bugünkü adını aldı.",
    },
  },
  {
    id: "marmara",
    university: "Marmara Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Göztepe / Kadıköy, Recep Tayyip Erdoğan Külliyesi ve diğer yerleşkeler",
    founded: "1883 kökler, 1982 üniversite statüsü",
    language: "Türkçe / seçili programlarda İngilizce",
    program: "Bilgisayar Mühendisliği",
    focus: "Çok kampüslü, geniş fakülte yapısı",
    website: "https://www.marmara.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.marmara.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=107290207" },
    ],
    compare: {
      university: "Marmara Üniversitesi",
      program: "Bilgisayar Mühendisliği",
      city: "İstanbul",
      rank: "",
      language: "Türkçe",
      curriculum: "21 fakülte, 12 enstitü, çok kampüslü yapı",
      labs: "Teknoloji Fakültesi üzerinden mühendislik odağı",
      notes: "1982'de üniversiteye dönüştü; kökleri 1883'e uzanır.",
    },
  },
  {
    id: "ytu",
    university: "Yıldız Teknik Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Yıldız ve Davutpaşa",
    founded: "1911 kökler, 1969 statü",
    language: "%30 İngilizce / Türkçe programlar",
    program: "Bilgisayar Mühendisliği (%30 İngilizce)",
    focus: "Mühendislik, uygulama ve güçlü fakülte yapısı",
    website: "https://www.yildiz.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.yildiz.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=110110031" },
    ],
    compare: {
      university: "Yıldız Teknik Üniversitesi",
      program: "Bilgisayar Mühendisliği (%30 İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "%30 İngilizce",
      curriculum: "Yıldız ve Davutpaşa kampüsleri, teknik fakülte ağı",
      labs: "Elektrik-Elektronik Fakültesi altında bilgisayar mühendisliği bölümü",
      notes: "Resmi tarihçe sayfası 1969'daki statü dönüşümünü vurgular.",
    },
  },
  {
    id: "koc",
    university: "Koç Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Rumelifeneri / Sarıyer",
    founded: "1993",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma yoğun, İngilizce eğitim, güçlü burs yapısı",
    website: "https://www.ku.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.ku.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=203910354" },
    ],
    compare: {
      university: "Koç Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Rumelifeneri kampüsü, araştırma odaklı mühendislik fakültesi",
      labs: "İngilizce eğitim ve güçlü laboratuvar/araştırma ortamı",
      notes: "1993'te kuruldu; ana kampüs 2000'de Rumelifeneri'ne taşındı.",
    },
  },
  {
    id: "sabanci",
    university: "Sabancı Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Tuzla",
    founded: "1999",
    language: "İngilizce",
    program: "Mühendislik ve Doğa Bilimleri Programları",
    focus: "Program seçme özgürlüğü, disiplinlerarası yapı",
    website: "https://www.sabanciuniv.edu/tr",
    sources: [
      { label: "Resmi site", url: "https://www.sabanciuniv.edu/tr" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=205110126" },
    ],
    compare: {
      university: "Sabancı Üniversitesi",
      program: "Mühendislik ve Doğa Bilimleri Programları",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Program seçme özgürlüğü ve disiplinlerarası yapı",
      labs: "Tuzla kampüsü ve yoğun yurt/lab altyapısı",
      notes: "İlk öğrencilerini 1999'da aldı; program bazlı değil, grup bazlı seçim yapar.",
    },
  },
  {
    id: "bilgi",
    university: "İstanbul Bilgi Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Kuştepe, Dolapdere, santralistanbul",
    founded: "1996",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Şehir içi kampüsler, İngilizce eğitim, uygulamalı yaklaşım",
    website: "https://www.bilgi.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.bilgi.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/2022/lisans-panel.php?p=1320&pr=1&y=202590344" },
    ],
    compare: {
      university: "İstanbul Bilgi Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Üç kampüs, MÜDEK onaylı mühendislik yaklaşımı",
      labs: "Laboratuvar odaklı ve staj imkanı güçlü program",
      notes: "1996'da kuruldu; eğitim dili sağlık bilimleri dışında İngilizcedir.",
    },
  },
  {
    id: "bau",
    university: "Bahçeşehir Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Beşiktaş ve çoklu yerleşkeler",
    founded: "1998",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "İngilizce eğitim, uluslararası odak, şehir merkezine yakınlık",
    website: "https://www.bahcesehir.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.bahcesehir.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=200510685" },
    ],
    compare: {
      university: "Bahçeşehir Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Beşiktaş ağırlıklı şehir kampüsü ve uluslararası yapı",
      labs: "İngilizce hazırlık zorunlu, teknik programlar İngilizce yürür",
      notes: "1998'den beri İstanbul'da; resmi hazırlık programı bulunur.",
    },
  },
  {
    id: "ozyegin",
    university: "Özyeğin Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Çekmeköy",
    founded: "2007",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma üniversitesi, modern kampüs ve sektör odaklı yaklaşım",
    website: "https://www.ozyegin.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.ozyegin.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=204890048" },
    ],
    compare: {
      university: "Özyeğin Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Çekmeköy kampüsü, modern sınıf ve laboratuvarlar",
      labs: "Araştırma üniversitesi ve güçlü kampüs olanakları",
      notes: "2007'de kuruldu; ilk öğrencilerini 2008'de aldı.",
    },
  },
];

export const researchChecklist = {
  tr: [
    "Bölümün ders planı güçlü mü?",
    "Hocaların çalışma alanları hedefinle uyumlu mu?",
    "Laboratuvar ve kulüp imkânları yeterli mi?",
    "Staj ve sektör bağlantısı ne kadar güçlü?",
    "İngilizce eğitim veya hazırlık seçeneği var mı?",
    "Şehir ve yaşam maliyeti sana uygun mu?",
  ],
  en: [
    "Is the curriculum strong?",
    "Do faculty interests match your goals?",
    "Are labs and student clubs active?",
    "How strong are internship and industry links?",
    "Is English education or prep available?",
    "Does the city and living cost fit you?",
  ],
};

export const talkQuestions = {
  tr: [
    "Bu bölümün en güzel tarafı ne?",
    "En zor tarafı ne?",
    "İlk yıl neye hazır olmak gerekir?",
    "Staj bulmak nasıl?",
    "Bugün tekrar tercih yapsan aynı bölümü seçer miydin?",
  ],
  en: [
    "What is the best part of this major?",
    "What is the hardest part?",
    "What should I be ready for in the first year?",
    "How hard is it to find internships?",
    "Would you choose the same major again today?",
  ],
};
