export const fieldKeys = ["software", "security", "hardware", "electronics"];

export const fields = [
  {
    id: "software",
    tone: "software",
    title: { tr: "Yazilim", en: "Software" },
    short: {
      tr: "Web, mobil, veri, yapay zeka ve urun gelistirme tarafina acilan esnek yol.",
      en: "A flexible path into web, mobile, data, AI, and product development.",
    },
    description: {
      tr: "Yazilim, problemleri kodla modelleyip calisan urunlere cevirmektir. Hata ayiklama, mantik kurma, kullanici dusunme ve surekli ogrenme bu alanin merkezindedir.",
      en: "Software turns problems into working products through code. Debugging, logic, user thinking, and continuous learning sit at the center of the field.",
    },
    likes: {
      tr: ["Problem cozmek", "Kodla bir sey uretmek", "Hizli prototip cikarmak", "Kendi basina arastirmak"],
      en: ["Solving problems", "Building with code", "Rapid prototyping", "Independent research"],
    },
    struggles: {
      tr: ["Uzun hata ayiklama sureleri", "Soyut dusunme", "Surekli yeni arac ogrenme", "Ekran basinda calisma"],
      en: ["Long debugging sessions", "Abstract thinking", "Learning new tools often", "Working at a screen"],
    },
    departments: {
      tr: ["Bilgisayar Muhendisligi", "Yazilim Muhendisligi", "Yapay Zeka Muhendisligi", "Yonetim Bilisim Sistemleri"],
      en: ["Computer Engineering", "Software Engineering", "AI Engineering", "Management Information Systems"],
    },
    daily: {
      tr: "Kod yazma, test etme, hata bulma, ekip ile karar alma ve kullanici problemini sade cozumlere bolme.",
      en: "Writing code, testing, debugging, making decisions with a team, and breaking user problems into smaller solutions.",
    },
    project: {
      title: { tr: "Bolum Secim Mini Sitesi", en: "Major Choice Mini Site" },
      time: { tr: "3 gun", en: "3 days" },
      difficulty: { tr: "Baslangic", en: "Beginner" },
      output: {
        tr: "Ana sayfa, 5 soruluk quiz ve sonuc ekrani olan kucuk site.",
        en: "A small site with a home page, 5-question quiz, and result screen.",
      },
    },
    strengths: {
      tr: ["Urun cikarma hizli olur", "Portfolyo yapmak kolaydir", "Birden fazla alana gecebilir"],
      en: ["Fast product output", "Easy to build a portfolio", "Can branch into many areas"],
    },
    cautions: {
      tr: ["Sadece video izlemek yetmez", "Hata ayiklama sabri gerekir", "Temel matematik ve algoritma onemlidir"],
      en: ["Watching videos is not enough", "Debugging patience matters", "Math and algorithms are important"],
    },
  },
  {
    id: "security",
    tone: "security",
    title: { tr: "Siber Guvenlik", en: "Cybersecurity" },
    short: {
      tr: "Sistemleri anlamak, riskleri bulmak ve savunmayi guclendirmek isteyenler icin.",
      en: "For people who want to understand systems, find risks, and strengthen defenses.",
    },
    description: {
      tr: "Siber guvenlik, yazilim, ag, isletim sistemi ve insan hatalarini birlikte dusunur. Etik sinir, dokuman okuma ve detay dikkati bu alanda cok onemlidir.",
      en: "Cybersecurity combines software, networks, operating systems, and human mistakes. Ethics, documentation, and attention to detail matter deeply.",
    },
    likes: {
      tr: ["Sistem kurcalamak", "Ag mantigini anlamak", "Detay yakalamak", "Yasal lablarda pratik yapmak"],
      en: ["Exploring systems", "Understanding networks", "Catching details", "Practicing in legal labs"],
    },
    struggles: {
      tr: ["Belirsiz hatalar", "Cok dokuman okumak", "Etik sinirlara dikkat etmek", "Temel yazilim/ag bilgisi eksigi"],
      en: ["Ambiguous issues", "Reading lots of docs", "Respecting ethical boundaries", "Missing software/network basics"],
    },
    departments: {
      tr: ["Bilgisayar Muhendisligi", "Yazilim Muhendisligi", "Siber Guvenlik Programlari", "Elektrik-Elektronik"],
      en: ["Computer Engineering", "Software Engineering", "Cybersecurity Programs", "Electrical-Electronics"],
    },
    daily: {
      tr: "Log okuma, ag trafigi inceleme, zafiyet arastirma, raporlama ve sistemleri daha guvenli hale getirme.",
      en: "Reading logs, inspecting network traffic, researching vulnerabilities, reporting, and hardening systems.",
    },
    project: {
      title: { tr: "Yasal Lab ve Linux Gorevi", en: "Legal Lab and Linux Task" },
      time: { tr: "3 gun", en: "3 days" },
      difficulty: { tr: "Baslangic-Orta", en: "Beginner-Intermediate" },
      output: {
        tr: "Temel Linux komutlari, IP/port/DNS notlari ve 2 kolay CTF/lab cozumu.",
        en: "Basic Linux commands, IP/port/DNS notes, and 2 easy CTF/lab solves.",
      },
    },
    strengths: {
      tr: ["Sistem dusunmeyi guclendirir", "Savunma ve analiz becerisi kazandirir", "Merakli insan icin derindir"],
      en: ["Builds systems thinking", "Develops defense and analysis skills", "Deep field for curious people"],
    },
    cautions: {
      tr: ["Izinsiz deneme yasal degildir", "Temel ag bilgisi gerekir", "Raporlama becerisi de onemlidir"],
      en: ["Unauthorized testing is illegal", "Network basics are required", "Reporting skills matter too"],
    },
  },
  {
    id: "hardware",
    tone: "hardware",
    title: { tr: "Donanim / Gomulu", en: "Hardware / Embedded" },
    short: {
      tr: "Kodun fiziksel dunyada sonuc vermesini sevenler icin sensor, kart ve robotik yolu.",
      en: "For people who like seeing code affect the physical world through sensors, boards, and robotics.",
    },
    description: {
      tr: "Donanim ve gomulu sistemler, yazilimi kartlar, sensorler, motorlar ve cihazlarla bulusturur. Sabirli test, dusuk seviye dusunme ve fiziksel prototip onemlidir.",
      en: "Hardware and embedded systems connect software with boards, sensors, motors, and devices. Patient testing, low-level thinking, and physical prototypes matter.",
    },
    likes: {
      tr: ["Arduino/ESP32 denemek", "Sensor okumak", "Robotik", "Kodun fiziksel sonucunu gormek"],
      en: ["Trying Arduino/ESP32", "Reading sensors", "Robotics", "Seeing physical output from code"],
    },
    struggles: {
      tr: ["Kablo/devre hatalari", "C/C++ zorlugu", "Yavas deneme dongusu", "Elektronik temel eksigi"],
      en: ["Wiring/circuit issues", "C/C++ difficulty", "Slower testing loops", "Missing electronics basics"],
    },
    departments: {
      tr: ["Bilgisayar Muhendisligi", "Elektrik-Elektronik", "Mekatronik", "Kontrol ve Otomasyon"],
      en: ["Computer Engineering", "Electrical-Electronics", "Mechatronics", "Control and Automation"],
    },
    daily: {
      tr: "Kart programlama, sensor verisi okuma, devre kontrolu, test yapma ve fiziksel prototip iyilestirme.",
      en: "Programming boards, reading sensor data, checking circuits, testing, and improving physical prototypes.",
    },
    project: {
      title: { tr: "Sensorlu Mini Sistem", en: "Mini Sensor System" },
      time: { tr: "3 gun", en: "3 days" },
      difficulty: { tr: "Orta", en: "Intermediate" },
      output: {
        tr: "Arduino/ESP32 veya simulator ile sensor verisi okuyup ekrana/LED'e yansitma.",
        en: "Read sensor data with Arduino/ESP32 or a simulator and show it on screen/LED.",
      },
    },
    strengths: {
      tr: ["Fiziksel urun hissi verir", "Robotik ve IoT'ye acilir", "Yazilim + elektronik koprusu kurar"],
      en: ["Feels like building a physical product", "Opens into robotics and IoT", "Bridges software and electronics"],
    },
    cautions: {
      tr: ["Parca ve ekipman gerekebilir", "Hatalar bazen koddan degil devreden gelir", "Sabirli olman gerekir"],
      en: ["Parts and equipment may be needed", "Bugs may come from circuits, not code", "Patience is required"],
    },
  },
  {
    id: "electronics",
    tone: "electronics",
    title: { tr: "Elektronik", en: "Electronics" },
    short: {
      tr: "Devre, sinyal, fizik ve sistem temeliyle daha derin muhendislik isteyenler icin.",
      en: "For people who want deeper engineering through circuits, signals, physics, and systems.",
    },
    description: {
      tr: "Elektronik, devrelerin, sinyallerin, guc sistemlerinin ve haberlesmenin temelini anlamaya odaklanir. Matematik ve fizikle arasi iyi olanlar icin guclu bir yoldur.",
      en: "Electronics focuses on understanding circuits, signals, power systems, and communication. It is a strong path for people comfortable with math and physics.",
    },
    likes: {
      tr: ["Devre analizi", "Fizik ve matematik", "Sinyal/haberlesme", "Laboratuvar calismasi"],
      en: ["Circuit analysis", "Physics and math", "Signals/communication", "Lab work"],
    },
    struggles: {
      tr: ["Teorik ders yogunlugu", "Matematik agirligi", "Soyut sinyal kavramlari", "Laboratuvar disiplini"],
      en: ["Heavy theory", "Math intensity", "Abstract signal concepts", "Lab discipline"],
    },
    departments: {
      tr: ["Elektrik-Elektronik Muhendisligi", "Elektronik ve Haberlesme", "Mekatronik", "Kontrol ve Otomasyon"],
      en: ["Electrical-Electronics Engineering", "Electronics and Communication", "Mechatronics", "Control and Automation"],
    },
    daily: {
      tr: "Devre tasarlama, olcum yapma, simule etme, sinyal yorumlama ve teoriyi fiziksel sistemlerle birlestirme.",
      en: "Designing circuits, measuring, simulating, interpreting signals, and connecting theory to physical systems.",
    },
    project: {
      title: { tr: "Devre Simulatoru Deneyi", en: "Circuit Simulator Experiment" },
      time: { tr: "3 gun", en: "3 days" },
      difficulty: { tr: "Baslangic-Orta", en: "Beginner-Intermediate" },
      output: {
        tr: "Direnc, LED, kondansator ve transistorle basit devre kurup calisma notu cikarma.",
        en: "Build a basic circuit with resistor, LED, capacitor, transistor and write notes about how it works.",
      },
    },
    strengths: {
      tr: ["Guclu muhendislik temeli verir", "Donanim ve haberlesmeye acilir", "Gomulu sistemleri daha iyi anlamayi saglar"],
      en: ["Gives a strong engineering base", "Opens into hardware and communication", "Helps understand embedded systems better"],
    },
    cautions: {
      tr: ["Matematik/fizik emegi ister", "Sonuc bazen yavas gelir", "Lab ve olcum dikkat ister"],
      en: ["Requires math/physics effort", "Results may come slowly", "Lab and measurement require care"],
    },
  },
];

export const questions = [
  {
    id: "q1",
    text: {
      tr: "Bir fikri kodla calisan bir urune cevirmek beni heyecanlandirir.",
      en: "Turning an idea into a working product with code excites me.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q2",
    text: {
      tr: "Bir sistemin neden guvensiz oldugunu anlamak ilgimi ceker.",
      en: "Understanding why a system is insecure interests me.",
    },
    weights: { software: 1, security: 3, hardware: 1, electronics: 0 },
  },
  {
    id: "q3",
    text: {
      tr: "Kodun bir sensor, LED, motor veya cihaz uzerinde sonuc vermesi hosuma gider.",
      en: "I like seeing code affect a sensor, LED, motor, or device.",
    },
    weights: { software: 1, security: 0, hardware: 3, electronics: 2 },
  },
  {
    id: "q4",
    text: {
      tr: "Devrelerin ve sinyallerin nasil calistigini merak ederim.",
      en: "I am curious about how circuits and signals work.",
    },
    weights: { software: 0, security: 0, hardware: 2, electronics: 3 },
  },
  {
    id: "q5",
    text: {
      tr: "Uzun sure hata ayiklamak beni hemen sogutmaz.",
      en: "Long debugging sessions do not discourage me quickly.",
    },
    weights: { software: 3, security: 2, hardware: 2, electronics: 1 },
  },
  {
    id: "q6",
    text: {
      tr: "Linux, ag, IP, port ve log gibi kavramlari ogrenmek isterim.",
      en: "I want to learn concepts like Linux, networks, IP, ports, and logs.",
    },
    weights: { software: 1, security: 3, hardware: 1, electronics: 0 },
  },
  {
    id: "q7",
    text: {
      tr: "Matematik ve fizik agirligi beni korkutmuyor.",
      en: "Math and physics intensity does not scare me.",
    },
    weights: { software: 1, security: 1, hardware: 2, electronics: 3 },
  },
  {
    id: "q8",
    text: {
      tr: "Kullaniciya faydali bir arayuz veya uygulama yapmak isterim.",
      en: "I want to build useful interfaces or apps for people.",
    },
    weights: { software: 3, security: 0, hardware: 0, electronics: 0 },
  },
  {
    id: "q9",
    text: {
      tr: "Detayli dokuman okuyup not almak bana uygun olabilir.",
      en: "Reading detailed documentation and taking notes may suit me.",
    },
    weights: { software: 2, security: 3, hardware: 1, electronics: 2 },
  },
  {
    id: "q10",
    text: {
      tr: "Kablo, kart, sensor ve fiziksel parcalarla ugrasmak isterim.",
      en: "I want to work with wires, boards, sensors, and physical parts.",
    },
    weights: { software: 0, security: 0, hardware: 3, electronics: 3 },
  },
  {
    id: "q11",
    text: {
      tr: "Bir problemi kucuk adimlara bolmek benim icin dogal.",
      en: "Breaking a problem into small steps feels natural to me.",
    },
    weights: { software: 3, security: 2, hardware: 2, electronics: 2 },
  },
  {
    id: "q12",
    text: {
      tr: "Etik sinirlara dikkat ederek guvenlik lablari cozmek isterim.",
      en: "I want to solve security labs while respecting ethical boundaries.",
    },
    weights: { software: 0, security: 3, hardware: 0, electronics: 0 },
  },
  {
    id: "q13",
    text: {
      tr: "Daha dusuk seviyeli C/C++ ve cihaz mantigi ilgimi ceker.",
      en: "Lower-level C/C++ and device logic interest me.",
    },
    weights: { software: 1, security: 1, hardware: 3, electronics: 2 },
  },
  {
    id: "q14",
    text: {
      tr: "Sinyal, haberlesme, elektrik ve olcum konulari bana yakin geliyor.",
      en: "Signals, communication, electricity, and measurement feel close to me.",
    },
    weights: { software: 0, security: 1, hardware: 1, electronics: 3 },
  },
  {
    id: "q15",
    text: {
      tr: "Portfolyo icin kendi projelerimi yayinlamak isterim.",
      en: "I want to publish my own projects for a portfolio.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q16",
    text: {
      tr: "Bir zafiyeti bulup sade raporlamak ilgimi ceker.",
      en: "Finding a vulnerability and reporting it clearly interests me.",
    },
    weights: { software: 1, security: 3, hardware: 0, electronics: 0 },
  },
  {
    id: "q17",
    text: {
      tr: "Fiziksel prototipte deneme-yanilma yapmak bana keyifli gelir.",
      en: "Trial and error on a physical prototype sounds enjoyable.",
    },
    weights: { software: 0, security: 0, hardware: 3, electronics: 2 },
  },
  {
    id: "q18",
    text: {
      tr: "Teorik konulari sabirla calisip derin anlamaya istekliyim.",
      en: "I am willing to study theory patiently and understand it deeply.",
    },
    weights: { software: 1, security: 1, hardware: 2, electronics: 3 },
  },
  {
    id: "q19",
    text: {
      tr: "Takimla uygulama gelistirmek ve geri bildirim almak isterim.",
      en: "I want to build apps with a team and get feedback.",
    },
    weights: { software: 3, security: 1, hardware: 1, electronics: 0 },
  },
  {
    id: "q20",
    text: {
      tr: "Sistemleri hem yazilim hem donanim tarafiyla anlamak isterim.",
      en: "I want to understand systems from both software and hardware sides.",
    },
    weights: { software: 1, security: 1, hardware: 3, electronics: 2 },
  },
];

export const t = {
  tr: {
    appName: "Bolum Pusulasi",
    nav: {
      landing: "Ana Sayfa",
      home: "Genel Bakis",
      test: "Alan Testi",
      results: "Sonuc",
      guide: "Alan Rehberi",
      projects: "Mini Gorevler",
      compare: "Universite",
      shortlist: "Tercihler",
      journal: "Gunluk",
      resources: "Kaynaklar",
      knowledge: "Atolye Notlari",
      workshop: "Atolye",
      pusula: "Bolum Pusulasi",
      project2: "Proje 2",
      project2Build: "Yapim Sureci",
      project2ScopeRecon: "Kapsam/Kesif",
      project2ExploitLab: "Exploit Lab",
      project2DnsExplorer: "DNS",
      project2WafSignals: "WAF",
      project2HostMap: "Host/VPS",
      project2TechFingerprint: "Teknoloji Izi",
      project2ExtensionAudit: "Eklenti Izinleri",
      project2FridaWorkbench: "Frida",
      project2WebQDashboard: "WebQ",
      project: "Proje",
      buildProcess: "Yapim Sureci",
      instructor: "Egitmen",
      homeworks: "Odevler",
      glossary: "Terimler Sozlugu",
      feedback: "Geri Bildirim",
    },
    common: {
      startTest: "Teste Basla",
      inspectFields: "Alanlari Incele",
      compareUniversities: "Universite Karsilastir",
      save: "Kaydet",
      add: "Ekle",
      delete: "Sil",
      clear: "Temizle",
      reset: "Yeniden Basla",
      close: "Kapat",
      next: "Ileri",
      back: "Geri",
      finish: "Testi Bitir",
      empty: "Henuz veri yok.",
      themeLight: "Gunduz",
      themeDark: "Gece",
      language: "Dil",
      viewMode: "Gorunum modu",
      compactMode: "Kompakt",
      visualizedMode: "Gorsel",
      official: "Resmi kaynak",
      open: "Ac",
      yourData: "Verilerin bu tarayicida saklanir.",
      footerCreditPrefix: "Derleyen, duzenleyen ve uygulayan",
    },
    home: {
      eyebrow: "Static karar araci",
      title: "Bolum secimi kafani karistirdiysa buradan basla.",
      subtitle:
        "Yazilim, siber guvenlik, donanim/gomulu sistem ve elektronik arasinda karar vermek icin test, mini gorev, gunluk ve tercih listesi bir arada.",
      quickStats: ["9 sayfa", "TR/EN", "Gece/gunduz", "Backend yok"],
      processTitle: "Karar sureci",
      process: ["Kisa testi coz", "Sonucunu incele", "Mini gorev dene", "Universiteleri karsilastir", "Karar cumleni yaz"],
      continueResult: "Kayitli sonuc var",
      noResult: "Henuz test sonucu yok",
    },
    test: {
      title: "Alan Testi",
      subtitle: "Her cumle icin sana ne kadar uydugunu sec. Sonuc kesin hukum degil; hangi alanlari denemen gerektigini gosterir.",
      scale: ["Hic uymuyor", "Az uyuyor", "Kararsizim", "Uyuyor", "Cok uyuyor"],
      answered: "cevaplandi",
      needAnswer: "Devam etmek icin bir secenek sec.",
    },
    results: {
      title: "Sonuc Analizi",
      subtitle: "Skorlar, ilgi ve deneme onceligini gosterir. En yuksek iki alani once denemen mantikli.",
      noResultTitle: "Sonuc icin once testi bitir.",
      topFields: "En yakin alanlar",
      strengths: "Guclu taraflar",
      cautions: "Dikkat noktalar",
      plan: "3 gunluk deneme plani",
      day1: "Gun 1: temel kavramlari ogren ve kucuk not al.",
      day2: "Gun 2: mini gorevin ilk calisan parcasini yap.",
      day3: "Gun 3: sonucu yaz, keyif/sabir/merak puani ver.",
    },
    guide: {
      title: "Alan Rehberi",
      subtitle: "Her alanin gunluk is tarzi, kimlere uygun oldugu ve hangi bolumlere baglandigi.",
      likes: "Kimler sever?",
      struggles: "Kimler zorlanir?",
      departments: "Ilgili bolumler",
      daily: "Gunluk is tarzi",
    },
    projects: {
      title: "Mini Proje Gorevleri",
      subtitle: "Ilgi alani dusunerek degil, kucuk deneylerle netlesir. Her alan icin 3 gunluk pratik gorev.",
      time: "Sure",
      difficulty: "Zorluk",
      output: "Beklenen cikti",
      ethics: "Guvenlik gorevlerinde sadece yasal egitim lablari kullan. Izinsiz deneme yapma.",
    },
    compare: {
      title: "Universite Karsilastirma",
      subtitle: "Aday bolumleri ayni kriterlerle yaz. Ilk surumda veriler tarayicinda localStorage ile tutulur.",
      university: "Universite",
      program: "Bolum",
      city: "Sehir",
      rank: "Basari sirasi",
      language: "Dil",
      campus: "Kampus",
      founded: "Kurulus",
      curriculum: "Ders plani puani",
      labs: "Lab / kulup / staj notu",
      notes: "Notlar",
      addToShortlist: "Tercihe ekle",
      saved: "Kayitli karsilastirmalar",
    },
    shortlist: {
      title: "Tercih Listesi",
      subtitle: "En guclu aday bolumleri sirala, neden istedigini yaz ve listeyi sade tut.",
      university: "Universite",
      program: "Bolum",
      reason: "Neden listede?",
      priority: "Oncelik",
      saved: "Kisa liste",
      moveUp: "Yukari al",
      moveDown: "Asagi al",
    },
    journal: {
      title: "Karar Gunlugu",
      subtitle: "Kararini yazili hale getir. Belirsizlik azalir, hangi adimi atman gerektigi daha net olur.",
      current: "Su an hangi alana yakininim?",
      why: "Neden?",
      excited: "Beni en cok ne heyecanlandiriyor?",
      worried: "Beni en cok ne korkutuyor?",
      experiment: "Bu hafta hangi mini denemeyi yapacagim?",
      finalSentence: "Son karar cumlem",
      summary: "Okunabilir ozet",
    },
    resources: {
      title: "Kaynaklar",
      subtitle: "Tercih icin son kontrolu resmi kaynaklardan yap. Buradaki site karar surecini kolaylastirir, resmi kilavuz yerine gecmez.",
      officialTitle: "Resmi kaynaklar",
      checklistTitle: "Bolum arastirma kontrol listesi",
      talkTitle: "Ogrenci/mezun sorulari",
      safetyTitle: "Guvenli ogrenme notu",
      safety: "Siber guvenlik pratigi sadece izinli lablarda ve egitim ortamlarinda yapilmali.",
    },
    knowledge: {
      title: "Atolye Notlari",
      subtitle: "Workshop boyunca islenen konularin interaktif ozeti. Konulari sirayla dene, ogrendiklerini isaretle.",
      progressLabel: "Ilerleme",
      topicsLabel: "konu ogrenildi",
      markLearned: "Ogrendim isaretle",
      learned: "Ogrenildi",
      unmark: "Isareti kaldir",
      previous: "Onceki konu",
      next: "Sonraki konu",
      randomReview: "Rastgele tekrar",
      resetProgress: "Ilerlemeyi sifirla",
      allDone: "Tebrikler, tum konulari isaretledin!",
      flipHint: "Kart ozetini gormek icin tikla",
      quickReview: "Hizli tekrar karti",
      dayAll: "Tum Gunler",
      day1: "1. Gun",
      day2: "2. Gun",
      placeholderBadge: "Yakinda",
      placeholderNote: "Bu konu henuz canli anlatimla doldurulmadi. Asagida o oturumda islenecek baslik taslagi var.",
      tocTitle: "Islenecek Basliklar",
      contribute: "Repo'ya Katki Yap",
    },
    landing: {
      eyebrow: "Atolye Ana Sayfasi",
      title: "Bilgisayar biliminin gercek dunyaya donustugu uygulamali bir AI atolyesi.",
      subtitle:
        "Bu atolyede once bilgisayar donanimi, yazilim, veri ve guvenlik temellerini akademik bir zeminle kurduk; sonra yazilim gelistirme, mimari dusunme, prompt engineering ve sistem guvenligi konularina derinlestik. En sonunda her kavrami gercek dunyadaki karsiligina dokunan pratik uygulamalarla, test edilebilir ve deterministik ciktilara donusturduk.",
      topicTags: [
        "Computational Thinking",
        "Hardware Literacy",
        "Software Architecture",
        "Data Security",
        "Secure SDLC",
        "Prompt Engineering",
        "Agentic Implementation",
        "Deterministic Testing",
      ],
      ctaNotes: "Not Atlasini Ac",
      ctaPusula: "Bolum Pusulasi'ni Kesfet",
      ctaProcess: "Yapim Surecini Gor",
      ctaInstructor: "Egitmeni Tani",
      notesTitle: "Bilgiden Sisteme: Atolye Haritasi",
      notesSubtitle:
        "Not kartlari ana sayfada yer kaplamiyor; tum konu atlasini modal icinde acip istedigin notun detayina geciyorsun.",
      notesSeeAll: "Not atlasini ac",
      notesModalCta: "Konu atlasini modalda incele",
      notesModalEyebrow: "Workshop Knowledge Atlas",
      notesModalTitle: "Atolye Notlari Atlasi",
      arcEyebrow: "Akademik Yolculuk",
      arcTitle: "Temel bilimden gercek sisteme, gercek sistemden guvenli urune.",
      arcSubtitle:
        "Dersin omurgasi sadece 'AI ile kod yazmak' degil; bilgisayarin fiziksel gerceginden yazilimin soyut mimarisine, verinin korunmasindan guvenli uygulama tasarimina uzanan tam bir muhendislik cizgisi.",
      learningArc: [
        {
          title: "Bilgisayar Bilimi Temeli",
          body: "Donanim, isletim sistemi, veri, ag ve yazilim kavramlarini ayni sistemin katmanlari olarak okuduk.",
        },
        {
          title: "Yazilim Gelistirme Derinligi",
          body: "Git, repo kulturu, dokumantasyon, mimari kararlar, test ve agent denetimini gercek projede uyguladik.",
        },
        {
          title: "Guvenlik ve Savunma Zihniyeti",
          body: "Web, DNS, WAF, host/VPS, extension riski, Frida ve WebQ konularini izinli ve etik sinirlarla isledik.",
        },
        {
          title: "Agentic AI Uretim Hatti",
          body: "Prompt engineering, planlama, arac kullanan ajanlar ve insan denetimiyle hizli ama kontrollu implementasyon kurduk.",
        },
      ],
      accelerationEyebrow: "Uygulamali AI Muhendisligi",
      accelerationTitle: "100x+ hiz, testli dogruluk ve mimari disiplin ayni hatta.",
      accelerationShort: "Agentic AI ile normal gelistirme ritminin cok otesinde, ama denetimli ve testlenebilir uretim.",
      accelerationBody:
        "Amac hizli demo degil: gercek dunya olaylarini modelleyen, olculebilir, tekrar uretilebilir ve dogrulanabilir implementasyonlar. Agentic AI burada sadece kod yazan bir asistan degil; prompt, mimari, test ve guvenlik refleksleriyle calisan bir uretim orkestrasyonu.",
      accelerationStats: [
        { value: "100x+", label: "Uretim ivmesi", body: "Normal insan ritmine gore cok daha hizli prototip, yine de commit, build ve test disipliniyle." },
        { value: "0-100", label: "Mimari hat", body: "Fikirden roadmap'e, component'ten dogrulanmis ekrana kadar izlenebilir uygulama." },
        { value: "TR/EN", label: "Akademik erisim", body: "Konu anlatimi, UI ve notlar iki dilde tasarlandi; kavram kaybi en aza indirildi." },
      ],
      pusulaTitle: "Proje: Bolum Pusulasi",
      pusulaSubtitle:
        "1. gun projesi: agentic AI araclariyla (Claude Code, Codex) bastan sona kodladigimiz gercek bir web uygulamasi. Universite bolum karari icin test, rehber, karsilastirma ve karar gunlugu sunar.",
      pusulaCta: "Projeyi Ac",
      processTitle: "Nasil Yapildi?",
      processSubtitle:
        "Bolum Pusulasi tek seferde degil, gercek commit'lerle adim adim ilerledi. Yapim Surecini incelersen agentic AI ile bir projenin nasil buyudugunu gorursun.",
      processCta: "Yapim Surecini Ac",
    },
    instructor: {
      title: "Egitmen",
      subtitle: "Bu atolyeyi hazirlayan ve sunan egitmen hakkinda kisa bilgi.",
      roleLabel: "Istinye Universitesi Meslek Yuksekokulu - Akademik Kadro",
      bio: "Bu atolyede yazilim gelistirme sureci, git/github pratikleri, agentic AI araclariyla calisma ve siber guvenlik icin gerekli temel mantik bilgisayar bolumu ogrencilerine anlatildi.",
      linksTitle: "Baglantilar",
      academicProfile: "Akademik Profil",
      github: "Github",
      linkedin: "LinkedIn",
      internshipTitle: "Yaz Arastirma Staji",
      internshipDesc: "Istinye Universitesi'nin yaz arastirma staji programi hakkinda guncel bilgi ve basvuru icin resmi sayfayi ziyaret et.",
      internshipCta: "Programi Incele",
      backToKnowledge: "Atolye Notlarina Don",
    },
    buildProcess: {
      title: "Yapim Sureci",
      subtitle:
        "Bolum Pusulasi tek buyuk adimda degil, gercek commit'lerle ilerledi. Bu zaman cizelgesi, agentic AI ile bir projenin nasil adim adim buyudugunu gosterir.",
      commitLabel: "Commit",
      filesTitle: "Neler degisti",
      lessonTitle: "Buradan cikan ders",
      liveBadge: "Su an devam ediyor",
      liveNote: "Atolye ve site, canli oturumlarda gelismeye devam ediyor; bu zaman cizelgesi surekli uzuyor.",
      relatedNote: "Ilgili not",
    },
    project2: {
      name: "Proje 2: Guvenlik Kesif Lab'i",
      kicker: "Day 2 Project",
      day2Badge: "2. gun notlari",
      buildTitle: "Proje 2 Yapim Sureci",
      buildSubtitle:
        "Bolum Pusulasi 1. gun projesi olarak kalir. Bu ikinci proje, 2. gun guvenlik notlarini egitim odakli, izinli ve savunma merkezli arayuzlere donusturur.",
      buildIntro:
        "Bu sayfa Proje 2'nin nasil buyuyecegini gosterir: once placeholder kabuklar, sonra her not icin guvenli simule edilen ozellikler.",
      placeholderBadge: "Placeholder",
      componentShell: "Bu sayfa henuz calisan arac degil; planlanan React component kabugunu ve kullanici deneyimini tarif eder.",
      functionalityTitle: "Sayfa / component islevi",
      placeholderBlocks: [
        { title: "Input", body: "Kullanici izinli hedef/kapsam veya egitim senaryosu girer." },
        { title: "Process", body: "Arayuz nottaki kavramlari zararsiz ve adim adim model olarak gosterir." },
        { title: "Output", body: "Sonuc savunma odakli rapor, kontrol listesi veya ogrenme ozeti olur." },
      ],
      relatedNotesTitle: "Bu sayfanin not baglantisi",
      relatedNotesBody: "Butona basinca ilgili Day 2 notu modal icinde acilir; sayfadan ayrilman gerekmez.",
      relatedNotesButton: "Ilgili notlar",
      openRelatedNotes: "Ilgili notlari modalda ac",
      modalEyebrow: "Workshop Notes",
      modalTitle: "Ilgili Day 2 Notlari",
    },
    homeworks: {
      title: "Odevler",
      subtitle: "Atolyede verilen odevler ve her biri icin adim adim katki rehberi.",
      numberLabel: "Odev",
    },
    glossary: {
      title: "Terimler Sozlugu",
      subtitle: "Atolyede islenen tum terimler, kisa aciklamalari ve gercek dunya ornekleriyle.",
      exampleLabel: "Gercek Dunya Ornegi",
      pendingBadge: "Katki Bekliyor",
      pendingNote: "Bu terimin ornegi henuz eklenmedi — Odev 3'te bunu sen ekleyebilirsin.",
    },
    feedback: {
      title: "Geri Bildirim",
      subtitle: "Atolyeye katilan ogrencilerin gercek gorusleri.",
      emptyTitle: "Henuz geri bildirim yok.",
      emptyBody: "Bu atolyeye katildin mi? Ilk geri bildirimi ekleyen sen ol.",
      ctaBody: "Geri bildirimini eklemek, git/github katki surecini gercek hayatta uygulamanin en iyi yolu. Adim adim rehber Odev 2'de.",
      ctaButton: "Odev 2'yi Ac",
    },
  },
  en: {
    appName: "Path Compass",
    nav: {
      landing: "Home",
      home: "Overview",
      test: "Field Test",
      results: "Results",
      guide: "Field Guide",
      projects: "Mini Tasks",
      compare: "University",
      shortlist: "Shortlist",
      journal: "Journal",
      resources: "Resources",
      knowledge: "Workshop Notes",
      workshop: "Workshop",
      pusula: "Path Compass",
      project2: "Project 2",
      project2Build: "Build Process",
      project2ScopeRecon: "Scope/Recon",
      project2ExploitLab: "Exploit Lab",
      project2DnsExplorer: "DNS",
      project2WafSignals: "WAF",
      project2HostMap: "Host/VPS",
      project2TechFingerprint: "Tech Fingerprint",
      project2ExtensionAudit: "Extension Audit",
      project2FridaWorkbench: "Frida",
      project2WebQDashboard: "WebQ",
      project: "Project",
      buildProcess: "Build Process",
      instructor: "Instructor",
      homeworks: "Homeworks",
      glossary: "Glossary",
      feedback: "Feedback",
    },
    common: {
      startTest: "Start Test",
      inspectFields: "Explore Fields",
      compareUniversities: "Compare Universities",
      save: "Save",
      add: "Add",
      delete: "Delete",
      clear: "Clear",
      reset: "Restart",
      close: "Close",
      next: "Next",
      back: "Back",
      finish: "Finish Test",
      empty: "No data yet.",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      viewMode: "View mode",
      compactMode: "Compact",
      visualizedMode: "Visualized",
      official: "Official source",
      open: "Open",
      yourData: "Your data stays in this browser.",
      footerCreditPrefix: "Collected, organized, and implemented by",
    },
    home: {
      eyebrow: "Static decision tool",
      title: "Not sure which university path fits you? Start here.",
      subtitle:
        "Use a test, mini tasks, a journal, and a shortlist to compare software, cybersecurity, hardware/embedded, and electronics.",
      quickStats: ["9 pages", "TR/EN", "Light/dark", "No backend"],
      processTitle: "Decision process",
      process: ["Take the short test", "Review your result", "Try a mini task", "Compare universities", "Write your decision sentence"],
      continueResult: "Saved result found",
      noResult: "No test result yet",
    },
    test: {
      title: "Field Test",
      subtitle: "Choose how much each sentence fits you. The result is not a final verdict; it shows which fields you should try first.",
      scale: ["Not at all", "A little", "Not sure", "Fits", "Fits strongly"],
      answered: "answered",
      needAnswer: "Pick an option to continue.",
    },
    results: {
      title: "Result Analysis",
      subtitle: "Scores show interest and experiment priority. Try the top two fields first.",
      noResultTitle: "Finish the test to see your result.",
      topFields: "Closest fields",
      strengths: "Strengths",
      cautions: "Watch points",
      plan: "3-day experiment plan",
      day1: "Day 1: learn the core concepts and take short notes.",
      day2: "Day 2: build the first working piece of the mini task.",
      day3: "Day 3: write what happened and score fun/patience/curiosity.",
    },
    guide: {
      title: "Field Guide",
      subtitle: "Daily work style, fit, difficulty, and related university majors for each field.",
      likes: "Who may like it?",
      struggles: "Who may struggle?",
      departments: "Related majors",
      daily: "Daily work style",
    },
    projects: {
      title: "Mini Project Tasks",
      subtitle: "You discover interest by trying, not only by thinking. Each field has a 3-day practical task.",
      time: "Time",
      difficulty: "Difficulty",
      output: "Expected output",
      ethics: "For security tasks, use only legal training labs. Do not test systems without permission.",
    },
    compare: {
      title: "University Comparison",
      subtitle: "Write candidate programs with the same criteria. In the first version, data is stored in your browser with localStorage.",
      university: "University",
      program: "Program",
      city: "City",
      rank: "Admission rank",
      language: "Language",
      campus: "Campus",
      founded: "Founded",
      curriculum: "Curriculum score",
      labs: "Lab / club / internship notes",
      notes: "Notes",
      addToShortlist: "Add to shortlist",
      saved: "Saved comparisons",
      featuredTitle: "Verified Istanbul universities",
      featuredSubtitle: "Ready-to-use profiles collected from official university and YOK Atlas pages.",
      featuredAction: "Add to comparison",
      officialSite: "Official site",
      profileBadge: "Verified profile",
    },
    shortlist: {
      title: "Shortlist",
      subtitle: "Rank your strongest candidate programs, write why they matter, and keep the list focused.",
      university: "University",
      program: "Program",
      reason: "Why is it listed?",
      priority: "Priority",
      saved: "Shortlist",
      moveUp: "Move up",
      moveDown: "Move down",
    },
    journal: {
      title: "Decision Journal",
      subtitle: "Put your thinking into words. Uncertainty shrinks and the next step becomes clearer.",
      current: "Which field feels closest right now?",
      why: "Why?",
      excited: "What excites me most?",
      worried: "What worries me most?",
      experiment: "Which mini experiment will I try this week?",
      finalSentence: "Final decision sentence",
      summary: "Readable summary",
    },
    resources: {
      title: "Resources",
      subtitle: "Use official sources for the final check. This site helps your decision process; it does not replace official guides.",
      officialTitle: "Official sources",
      checklistTitle: "Program research checklist",
      talkTitle: "Questions for students/graduates",
      safetyTitle: "Safe learning note",
      safety: "Cybersecurity practice should only happen in permitted labs and training environments.",
    },
    knowledge: {
      title: "Workshop Notes",
      subtitle: "An interactive summary of the topics covered in the workshop. Go through them in order and mark what you've learned.",
      progressLabel: "Progress",
      topicsLabel: "topics learned",
      markLearned: "Mark as learned",
      learned: "Learned",
      unmark: "Unmark",
      previous: "Previous topic",
      next: "Next topic",
      randomReview: "Random review",
      resetProgress: "Reset progress",
      allDone: "Nice work, you've marked every topic!",
      flipHint: "Click the card to see the summary",
      quickReview: "Quick review card",
      dayAll: "All Days",
      day1: "Day 1",
      day2: "Day 2",
      placeholderBadge: "Coming soon",
      placeholderNote: "This topic hasn't been taught live yet. Here's the draft outline for that session.",
      tocTitle: "Topics to Cover",
      contribute: "Contribute on the Repo",
    },
    landing: {
      eyebrow: "Workshop Home",
      title: "An applied AI workshop where computer science becomes real software.",
      subtitle:
        "We did not only cover building software with agentic AI. We started with computer hardware, software, data, and security foundations; then went deeper into software development, architecture, prompt engineering, and securing systems. Finally, we turned each concept into practical real-world implementations that can be tested, verified, and made deterministic.",
      topicTags: [
        "Computational Thinking",
        "Hardware Literacy",
        "Software Architecture",
        "Data Security",
        "Secure SDLC",
        "Prompt Engineering",
        "Agentic Implementation",
        "Deterministic Testing",
      ],
      ctaNotes: "Open Notes Atlas",
      ctaPusula: "Explore Path Compass",
      ctaProcess: "See the Build Process",
      ctaInstructor: "Meet the Instructor",
      notesTitle: "From Knowledge to Systems: Workshop Map",
      notesSubtitle:
        "Note cards no longer occupy the homepage; open the topic atlas in a modal and jump into any detailed note from there.",
      notesSeeAll: "Open notes atlas",
      notesModalCta: "Explore the topic atlas in a modal",
      notesModalEyebrow: "Workshop Knowledge Atlas",
      notesModalTitle: "Workshop Notes Atlas",
      arcEyebrow: "Academic Journey",
      arcTitle: "From foundations to real systems, from real systems to secure products.",
      arcSubtitle:
        "The spine of the course is not just 'coding with AI'. It is a full engineering line from the physical reality of computers to software architecture, data protection, secure product thinking, and tested implementation.",
      learningArc: [
        {
          title: "Computer Science Grounding",
          body: "We read hardware, operating systems, data, networks, and software as layers of one living system.",
        },
        {
          title: "Software Development Depth",
          body: "We practiced Git, repository culture, documentation, architecture decisions, testing, and agent output review inside a real project.",
        },
        {
          title: "Security and Defense Mindset",
          body: "We covered web, DNS, WAF, host/VPS, extension risk, Frida, and WebQ inside authorized and ethical boundaries.",
        },
        {
          title: "Agentic AI Production Line",
          body: "We combined prompt engineering, planning, tool-using agents, and human review into fast but controlled implementation.",
        },
      ],
      accelerationEyebrow: "Applied AI Engineering",
      accelerationTitle: "100x+ speed, tested accuracy, and architectural discipline on the same line.",
      accelerationShort: "Agentic AI moves far beyond ordinary development rhythm, but remains reviewed, tested, and measurable.",
      accelerationBody:
        "The target is not a fast demo. The target is implementation that models real-world occurrences, can be measured, reproduced, verified, and improved. Agentic AI here is not merely a code assistant; it is production orchestration across prompts, architecture, tests, and security reflexes.",
      accelerationStats: [
        { value: "100x+", label: "Production acceleration", body: "Much faster prototyping than normal human rhythm, still shaped by commits, builds, and tests." },
        { value: "0-100", label: "Architecture line", body: "Traceable implementation from idea to roadmap, component, and verified screen." },
        { value: "TR/EN", label: "Academic access", body: "Concepts, UI, and notes are designed bilingually to reduce meaning loss." },
      ],
      pusulaTitle: "Project: Path Compass",
      pusulaSubtitle:
        "Day 1 project: a real web app built end-to-end in this workshop with agentic AI tools (Claude Code, Codex): a test, guide, comparison tool, and decision journal for choosing a university major.",
      pusulaCta: "Open the Project",
      processTitle: "How Was It Built?",
      processSubtitle:
        "Path Compass didn't appear all at once — it grew commit by commit. Check the Build Process to see how a project grows with agentic AI.",
      processCta: "Open the Build Process",
    },
    instructor: {
      title: "Instructor",
      subtitle: "A short introduction to the instructor who prepared and delivered this workshop.",
      roleLabel: "Istinye University Vocational School - Academic Staff",
      bio: "In this workshop, computer department students learned about the software development process, git/github practices, working with agentic AI tools, and the core logic needed for cybersecurity.",
      linksTitle: "Links",
      academicProfile: "Academic Profile",
      github: "Github",
      linkedin: "LinkedIn",
      internshipTitle: "Summer Research Internship",
      internshipDesc: "Visit the official page for up-to-date information and applications for Istinye University's summer research internship program.",
      internshipCta: "View the Program",
      backToKnowledge: "Back to Workshop Notes",
    },
    buildProcess: {
      title: "Build Process",
      subtitle:
        "Path Compass grew through real commits, not one giant leap. This timeline shows how a project grows step by step with agentic AI.",
      commitLabel: "Commit",
      filesTitle: "What changed",
      lessonTitle: "The takeaway",
      liveBadge: "In progress right now",
      liveNote: "The workshop and this site keep evolving in live sessions; this timeline keeps growing.",
      relatedNote: "Related note",
    },
    project2: {
      name: "Project 2: Security Recon Lab",
      kicker: "Day 2 Project",
      day2Badge: "Day 2 notes",
      buildTitle: "Project 2 Build Process",
      buildSubtitle:
        "Path Compass remains the Day 1 project. This second project turns the Day 2 security notes into educational, authorized, defense-centered interfaces.",
      buildIntro:
        "This page shows how Project 2 will grow: placeholder shells first, then safely simulated features for each note.",
      placeholderBadge: "Placeholder",
      componentShell: "This page is not a working tool yet; it describes the planned React component shell and user experience.",
      functionalityTitle: "Page / component functionality",
      placeholderBlocks: [
        { title: "Input", body: "The user enters an authorized target/scope or a learning scenario." },
        { title: "Process", body: "The UI shows the note concepts as harmless, step-by-step models." },
        { title: "Output", body: "The result becomes a defense-focused report, checklist, or learning summary." },
      ],
      relatedNotesTitle: "Note connection for this page",
      relatedNotesBody: "Press the button to open the related Day 2 note inside a modal without leaving the page.",
      relatedNotesButton: "Related notes",
      openRelatedNotes: "Open related notes in modal",
      modalEyebrow: "Workshop Notes",
      modalTitle: "Related Day 2 Notes",
    },
    homeworks: {
      title: "Homeworks",
      subtitle: "The homeworks assigned in this workshop, each with a step-by-step contribution guide.",
      numberLabel: "Homework",
    },
    glossary: {
      title: "Glossary",
      subtitle: "Every term covered in the workshop, with a short description and a real-world example.",
      exampleLabel: "Real-World Example",
      pendingBadge: "Awaiting Contribution",
      pendingNote: "This term's example hasn't been added yet — you can add it in Homework 3.",
    },
    feedback: {
      title: "Feedback",
      subtitle: "Real feedback from students who joined this workshop.",
      emptyTitle: "No feedback yet.",
      emptyBody: "Did you join this workshop? Be the first to add your feedback.",
      ctaBody: "Adding your feedback is the best way to practice the git/github contribution flow for real. The step-by-step guide is in Homework 2.",
      ctaButton: "Open Homework 2",
    },
  },
};

export const resources = [
  {
    title: "YOK Atlas",
    href: "https://yokatlas.yok.gov.tr/",
    desc: {
      tr: "Program, basari sirasi, kontenjan ve universite arastirmasi icin resmi kaynak.",
      en: "Official source for program, ranking, quota, and university research.",
    },
  },
  {
    title: "OSYM",
    href: "https://www.osym.gov.tr/",
    desc: {
      tr: "Sinav, kilavuz, duyuru ve nihai tercih kosullari icin resmi kaynak.",
      en: "Official source for exams, guides, announcements, and final preference rules.",
    },
  },
  {
    title: "OSYM 2026-YKS Kilavuzu",
    href: "https://www.osym.gov.tr/TR%2C33851/2026-yuksekogretim-kurumlari-sinavi-yks-kilavuzu.html",
    desc: {
      tr: "2026 YKS sureci icin kilavuz ve ilgili dokumanlar.",
      en: "Guide and related documents for the 2026 YKS process.",
    },
  },
];

export const featuredUniversities = [
  {
    id: "boun",
    university: "Boğaziçi Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Bebek / Rumeli Hisarı",
    founded: "1863 kökler, 1971 resmi ad",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma odaklı, uluslararası ve güçlü mühendislik geleneği",
    website: "https://www.boun.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.boun.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=102210277" },
    ],
    compare: {
      university: "Boğaziçi Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Bebek / Rumeli Hisarı, araştırma odaklı profil",
      labs: "Güçlü akademik kadro ve uluslararası eğitim dili",
      notes: "Kökleri 1863'e dayanan, resmi adı 1971'de alınan üniversite.",
    },
  },
  {
    id: "itu",
    university: "İstanbul Teknik Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Ayazağa, Gümüşsuyu, Maçka, Taşkışla, Tuzla",
    founded: "1773",
    language: "İngilizce / %30 İngilizce programlar",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Mühendislik, araştırma ve teknik altyapı",
    website: "https://www.itu.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.itu.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=105510608" },
    ],
    compare: {
      university: "İstanbul Teknik Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "13 fakülte, 99 lisans programı",
      labs: "Beş kampüs, güçlü laboratuvar ve araştırma altyapısı",
      notes: "1773'e uzanan köklü teknik üniversite.",
    },
  },
  {
    id: "istanbul",
    university: "İstanbul Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Beyazıt / Fatih ve diğer yerleşkeler",
    founded: "1933",
    language: "Türkçe / seçili programlarda İngilizce",
    program: "Yapay Zeka ve Veri Mühendisliği (İngilizce)",
    focus: "Tarihsel kökler, geniş akademik yapı, merkez kampüs",
    website: "https://www.istanbul.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.istanbul.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=105690984" },
    ],
    compare: {
      university: "İstanbul Üniversitesi",
      program: "Yapay Zeka ve Veri Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Merkez kampüs ve geniş akademik fakülte yapısı",
      labs: "Bilgisayar ve Bilişim Teknolojileri Fakültesi üzerinden örnek program",
      notes: "1933 Üniversite Reformu ile bugünkü adını aldı.",
    },
  },
  {
    id: "marmara",
    university: "Marmara Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Göztepe / Kadıköy, Recep Tayyip Erdoğan Külliyesi ve diğer yerleşkeler",
    founded: "1883 kökler, 1982 üniversite statüsü",
    language: "Türkçe / seçili programlarda İngilizce",
    program: "Bilgisayar Mühendisliği",
    focus: "Çok kampüslü, geniş fakülte yapısı",
    website: "https://www.marmara.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.marmara.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=107290207" },
    ],
    compare: {
      university: "Marmara Üniversitesi",
      program: "Bilgisayar Mühendisliği",
      city: "İstanbul",
      rank: "",
      language: "Türkçe",
      curriculum: "21 fakülte, 12 enstitü, çok kampüslü yapı",
      labs: "Teknoloji Fakültesi üzerinden mühendislik odağı",
      notes: "1982'de üniversiteye dönüştü; kökleri 1883'e uzanır.",
    },
  },
  {
    id: "ytu",
    university: "Yıldız Teknik Üniversitesi",
    type: "Devlet",
    city: "İstanbul",
    campus: "Yıldız ve Davutpaşa",
    founded: "1911 kökler, 1969 statü",
    language: "%30 İngilizce / Türkçe programlar",
    program: "Bilgisayar Mühendisliği (%30 İngilizce)",
    focus: "Mühendislik, uygulama ve güçlü fakülte yapısı",
    website: "https://www.yildiz.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.yildiz.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=110110031" },
    ],
    compare: {
      university: "Yıldız Teknik Üniversitesi",
      program: "Bilgisayar Mühendisliği (%30 İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "%30 İngilizce",
      curriculum: "Yıldız ve Davutpaşa kampüsleri, teknik fakülte ağı",
      labs: "Elektrik-Elektronik Fakültesi altında bilgisayar mühendisliği bölümü",
      notes: "Resmi tarihçe sayfası 1969'daki statü dönüşümünü vurgular.",
    },
  },
  {
    id: "koc",
    university: "Koç Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Rumelifeneri / Sarıyer",
    founded: "1993",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma yoğun, İngilizce eğitim, güçlü burs yapısı",
    website: "https://www.ku.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.ku.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=203910354" },
    ],
    compare: {
      university: "Koç Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Rumelifeneri kampüsü, araştırma odaklı mühendislik fakültesi",
      labs: "İngilizce eğitim ve güçlü laboratuvar/araştırma ortamı",
      notes: "1993'te kuruldu; ana kampüs 2000'de Rumelifeneri'ne taşındı.",
    },
  },
  {
    id: "sabanci",
    university: "Sabancı Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Tuzla",
    founded: "1999",
    language: "İngilizce",
    program: "Mühendislik ve Doğa Bilimleri Programları",
    focus: "Program seçme özgürlüğü, disiplinlerarası yapı",
    website: "https://www.sabanciuniv.edu/tr",
    sources: [
      { label: "Resmi site", url: "https://www.sabanciuniv.edu/tr" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=205110126" },
    ],
    compare: {
      university: "Sabancı Üniversitesi",
      program: "Mühendislik ve Doğa Bilimleri Programları",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Program seçme özgürlüğü ve disiplinlerarası yapı",
      labs: "Tuzla kampüsü ve yoğun yurt/lab altyapısı",
      notes: "İlk öğrencilerini 1999'da aldı; program bazlı değil, grup bazlı seçim yapar.",
    },
  },
  {
    id: "bilgi",
    university: "İstanbul Bilgi Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Kuştepe, Dolapdere, santralistanbul",
    founded: "1996",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Şehir içi kampüsler, İngilizce eğitim, uygulamalı yaklaşım",
    website: "https://www.bilgi.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.bilgi.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/2022/lisans-panel.php?p=1320&pr=1&y=202590344" },
    ],
    compare: {
      university: "İstanbul Bilgi Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Üç kampüs, MÜDEK onaylı mühendislik yaklaşımı",
      labs: "Laboratuvar odaklı ve staj imkanı güçlü program",
      notes: "1996'da kuruldu; eğitim dili sağlık bilimleri dışında İngilizcedir.",
    },
  },
  {
    id: "bau",
    university: "Bahçeşehir Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Beşiktaş ve çoklu yerleşkeler",
    founded: "1998",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "İngilizce eğitim, uluslararası odak, şehir merkezine yakınlık",
    website: "https://www.bahcesehir.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.bahcesehir.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=200510685" },
    ],
    compare: {
      university: "Bahçeşehir Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Beşiktaş ağırlıklı şehir kampüsü ve uluslararası yapı",
      labs: "İngilizce hazırlık zorunlu, teknik programlar İngilizce yürür",
      notes: "1998'den beri İstanbul'da; resmi hazırlık programı bulunur.",
    },
  },
  {
    id: "ozyegin",
    university: "Özyeğin Üniversitesi",
    type: "Vakıf",
    city: "İstanbul",
    campus: "Çekmeköy",
    founded: "2007",
    language: "İngilizce",
    program: "Bilgisayar Mühendisliği (İngilizce)",
    focus: "Araştırma üniversitesi, modern kampüs ve sektör odaklı yaklaşım",
    website: "https://www.ozyegin.edu.tr/",
    sources: [
      { label: "Resmi site", url: "https://www.ozyegin.edu.tr/" },
      { label: "YÖK Atlas", url: "https://yokatlas.yok.gov.tr/lisans.php?y=204890048" },
    ],
    compare: {
      university: "Özyeğin Üniversitesi",
      program: "Bilgisayar Mühendisliği (İngilizce)",
      city: "İstanbul",
      rank: "",
      language: "İngilizce",
      curriculum: "Çekmeköy kampüsü, modern sınıf ve laboratuvarlar",
      labs: "Araştırma üniversitesi ve güçlü kampüs olanakları",
      notes: "2007'de kuruldu; ilk öğrencilerini 2008'de aldı.",
    },
  },
];

export const researchChecklist = {
  tr: [
    "Bolumun ders plani guclu mu?",
    "Hocalarin alanlari hedefinle uyumlu mu?",
    "Laboratuvar ve kulup imkanlari var mi?",
    "Staj ve sektor baglantisi nasil?",
    "Ingilizce egitim veya hazirlik var mi?",
    "Sehir ve yasam maliyeti sana uygun mu?",
  ],
  en: [
    "Is the curriculum strong?",
    "Do faculty interests match your goals?",
    "Are labs and student clubs active?",
    "How strong are internship and industry links?",
    "Is English education or prep available?",
    "Does the city and living cost fit you?",
  ],
};

export const talkQuestions = {
  tr: [
    "Bu bolumun en guzel tarafi ne?",
    "En zor tarafi ne?",
    "Ilk sene neye hazir olmak lazim?",
    "Staj bulmak nasil?",
    "Bugun tekrar tercih yapsan ayni bolumu secer miydin?",
  ],
  en: [
    "What is the best part of this major?",
    "What is the hardest part?",
    "What should I be ready for in the first year?",
    "How hard is it to find internships?",
    "Would you choose the same major again today?",
  ],
};
